### PR TITLE
gf: fix crash on a compile hint with a `where`

### PR DESCRIPTION
**Pull request by levy**
```julia
precompile(Tuple{typeof(-), T, T} where T<:Union{Int128, Int64, UInt128, UInt64})
```
faults on master and returns on 1.13.0.

`egal_normalize_hint_types` reads its argument as a tuple type and calls `jl_nparams` on it. A `UnionAll` has no such field, so the read lands on a null address. A `where` signature keeps its parameters under the `where`, so no slot at this level is a closed `Type{A}` to narrow: the normalization leaves it alone, and the matching that follows takes it as it always did.

The regression comes from #61323. A test in `test/precompile.jl` covers the three shapes.

**Disclosure:** developed with Claude Code (Opus 5) under my direction. It wrote the code and this text; the measurements were run on my machine. I reviewed the changes. The commits carry an Assisted-by trailer.

### CODE REVIEW

File: src/gf.c [hunk 1]
```diff
@@ -4348,6 +4348,10 @@ jl_value_t *jl_get_specialization1(jl_tupletype_t *types, size_t world)
 // stays: the bottom object is the unique instance of its `Type`.
 static jl_tupletype_t *egal_normalize_hint_types(jl_tupletype_t *types JL_PROPAGATES_ROOT) JL_CANSAFEPOINT
 {
+    // a `where` signature arrives as a `UnionAll`: its parameters sit under the
```
Comment (adienes) [inline src/gf.c:4351]: fyi, I think it's better to almost entirely omit the ai comments

Comment (levy) [reply src/gf.c:4351]: All right, I wasn't sure if they are useful or just noise. I'll leave them out in the future.
