### PR TITLE
alloc profiler: fix analyzegc error

### PR DESCRIPTION
**Pull request by vilterp**
Get the thread id with a different function that's also `JL_NOTSAFEPOINT`.

Fixes the analyzegc build failure introduced by https://github.com/JuliaLang/julia/pull/42768.

### CODE REVIEW

**Comment by vilterp** [comment]
Sigh. New analyzegc error:

```
/cache/build/default-amdci5-1/julialang/julia-master/src/gc-alloc-profiler.cpp:135:9: error: Calling potential safepoint from function annotated JL_NOTSAFEPOINT [julia.GCChecker]
--
  | get_raw_backtrace(),
  | ^~~~~~~~~~~~~~~~~~~
```

**Review by NHDaly — APPROVED** [review]
Thank you @vilterp. Fixed! Thanks @Keno and @DilumAluthge for catching the build failure 👍 👍

**Comment by vilterp** [comment]
Thanks Valentin :)
