### ISSUE TITLE
Build failure with llvm-4.0.1

### ISSUE THREAD

**Issue by wavexx** [JuliaLang/julia#22597]
Attempting to rebuild julia from the master branch today I hit this error pretty late in the build process:

```
...
docs/Docs.jl
/home/ydelia/downloads/src/julia/base/precompile.jl
ptrtoint not supported for non-integral pointers
ptrtoint not supported for non-integral pointers
ptrtoint not supported for non-integral pointers
ptrtoint not supported for non-integral pointers
LLVM ERROR: Broken function found, compilation aborted!
*** This error is usually fixed by running `make clean`. If the error persists, try `make cleanall`. ***
Makefile:233: recipe for target '/home/ydelia/downloads/src/julia/usr/lib/julia/sys.o' failed
make[1]: *** [/home/ydelia/downloads/src/julia/usr/lib/julia/sys.o] Error 1
Makefile:109: recipe for target 'julia-sysimg-release' failed
make: *** [julia-sysimg-release] Error 2
```

I'm using system's llvm-4.0.1 from debian unstable.
This is already a fresh build.

**Comment by tkelman** [comment]
It'll need a bunch of patches, ref https://github.com/JuliaLang/julia/blob/f4501ffcfade1877648b69c3d866c02df5a118d3/deps/llvm.mk#L472-L488. We can try to make sure everything we need makes it in to LLVM 5.0, but for now we don't really support building against unpatched system LLVM.

**Comment by wavexx** [comment]
On Wed, Jun 28 2017, Tony Kelman wrote:
> We can try to make sure everything we need makes it in to LLVM 5.0,
> but for now we don't really support building against unpatched system
> LLVM.

Ok. I was trying to avoid building a custom llvm, as it's by far the
longest part of the build and takes up considerable space.

I tried to build with debian's llvm-5.0 as well, but I ran into a build
failure with src/llvm-late-gc-lowering.cpp (incorrect parameters calling
AllocaInst).

Should I report it?

**Comment by wavexx** [comment]
On Wed, Jun 28 2017, Yuri D'Elia wrote:
> I tried to build with debian's llvm-5.0 as well, but I ran into a build
> failure with src/llvm-late-gc-lowering.cpp (incorrect parameters calling
> AllocaInst).

For instance:

    CC src/llvm-late-gc-lowering.o
In file included from /usr/lib/llvm-5.0/include/llvm/ADT/SmallPtrSet.h:18:0,
                 from /usr/lib/llvm-5.0/include/llvm/ADT/PostOrderIterator.h:21,
                 from /home/ydelia/downloads/src/julia/src/llvm-late-gc-lowering.cpp:4:
/usr/lib/llvm-5.0/include/llvm/Config/abi-breaking.h:23:6: warning: "LLVM_DISABLE_ABI_BREAKING_CHECKS_ENFORCING" is not defined [-Wundef]
 #if !LLVM_DISABLE_ABI_BREAKING_CHECKS_ENFORCING
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ydelia/downloads/src/julia/src/llvm-late-gc-lowering.cpp: In member function ‘bool LateLowerGCFrame::CleanupIR(llvm::Function&)’:
/home/ydelia/downloads/src/julia/src/llvm-late-gc-lowering.cpp:1096:69: error: invalid conversion from ‘llvm::Constant*’ to ‘unsigned int’ [-fpermissive]
     AllocaInst *Frame = new AllocaInst(T_prjlvalue, ConstantInt::get(T_int32, maxframeargs),
                                                     ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/ydelia/downloads/src/julia/src/llvm-late-gc-lowering.cpp:11:0:
/usr/lib/llvm-5.0/include/llvm/IR/Instructions.h:75:12: note:   initializing argument 2 of ‘llvm::AllocaInst::AllocaInst(llvm::Type*, unsigned int, llvm::Value*, const llvm::Twine&, llvm::Instruction*)’
   explicit AllocaInst(Type *Ty, unsigned AddrSpace,
            ^~~~~~~~~~
Makefile:138: recipe for target 'llvm-late-gc-lowering.o' failed

**Comment by yuyichao** [comment]
LLVM 5.0 build is not expected to work right now either due to patches that aren't upstreamed. (The failure you see isn't that though there will be build failure even if that pass)
