### ISSUE TITLE
Apple ARM64 debug build broken

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#45181]
```
    LINK build/dev/usr/lib/libjulia-internal-debug.1.9.dylib
Undefined symbols for architecture arm64:
  "_ptrauth_strip", referenced from:
      _jl_rec_backtrace in stackwalk.dbg.obj
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Caused by https://github.com/JuliaLang/julia/pull/45110.

**Comment by gbaraldi** [comment]
The function probably needed to be `static inline`
