### ISSUE TITLE
Compilation failure on x86 with Clang (task.c inline asm)

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#14230]
The `ASM_COPY_STACKS` inline assembly fails to compile on x86 with Clang 3.5 (Debian Jessie):

```
task.c:343:37: error: invalid input constraint '' in asm
                : : "r"(stackbase), ""(&start_task) : "memory" );
```

Switching the constraint back to `i` (as it was before fc300bc) also doesn't work:

```
task.c:338:17: error: invalid operand for inline asm constraint 'i'
            asm(" movl %0, %%esp;\n"
```

GCC does compile the assembly without issue. According to [this Clang issue](https://llvm.org/bugs/show_bug.cgi?id=11657) this seems like proper behaviour..

cc @vtjnash

**Comment by vtjnash** [comment]
i have a fix for this in https://github.com/JuliaLang/julia/pull/13099/files#diff-e33939bb54b7505cfc2f5d12b60d0a9cR996

**Comment by maleadt** [comment]
Ah I see, I'll be waiting for that to land then.
I got past the error by `make`ing the object file in question with `USECLANG=0`, so it's not really a pressing issue.

**Comment by KristofferC** [comment]
Please repoen if still applicable.
