### ISSUE TITLE
Build error with ICC 15.0.2

### ISSUE THREAD

**Issue by kshyatt** [JuliaLang/julia#14595]
`git bisect` shows me this was "introduced" at 82e91180ec4ce29c0b892afeee00f567c04822d5 by @drepper. Can anyone reproduce? It seems like `icc` is not being honest about whether it is `gcc` compatible.
```bash
    CC src/codegen.o
/home/kshyatt/julia/v0.5/src/codegen.cpp(4706): error: expression must be a modifiable lvalue
          JL_MARK_INITIALIZED(SP);
          ^
```

```bash
icc -v
icc version 15.0.2 (gcc version 4.8.2 compatibility)
```

**Comment by yuyichao** [comment]
I personally prefer to just initialize the variable even when it's not necessary in these cases. It's very hard (or at least no one will actually do that) to go through all the variables that are wrongly marked as initialized when making change to the code.

**Comment by drepper** [comment]
On Thu, Jan 7, 2016 at 5:33 PM, Katharine Hyatt <notifications@github.com>
wrote:
>
> /home/kshyatt/julia/v0.5/src/codegen.cpp(4706): error: expression must be a modifiable lvalue
>           JL_MARK_INITIALIZED(SP);
>           ^
>
>
If this creates a problem then it is icc's fault since it claims to be gcc
compatible but isn't.  Is there a way to force icc to not claim to be gcc
compatible?  Otherwise you'll have to find a way to distinguish icc from
gcc and conditionally define the macro.  I have no access to that compiler.

**Comment by kshyatt** [comment]
> If this creates a problem then it is icc's fault since it claims to be gcc
compatible but isn't.
> Otherwise you'll have to find a way to distinguish icc from
gcc and conditionally define the macro. 

@yuyichao says there's probably a simple way to do this in `julia.h`. I'll give it a try later today.

**Comment by drepper** [comment]
On Thu, Jan 7, 2016 at 5:44 PM, Yichao Yu <notifications@github.com> wrote:

> I personally prefer to just initialize the variable even when it's not
> necessary in these cases. It's very hard (or at least no one will actually
> do that) to go through all the variables that are wrongly marked as
> initialized when making change to the code.
>
Easier said then done.  Sometimes (as in this specific case) the variable
in question has no simple type.  In this case the type depends on the llvm
version used.  Having conditional code just to unnecessarily initialize a
variable is IMO much worse.  Just once and for all define the macro
correctly.  As I wrote in the other email, it's actually a compiler bug
that's causing the problem.

**Comment by yuyichao** [comment]
I don't understand why it's not handled by simply

```diff
a/src/codegen.cpp b/src/codegen.cpp
index 604b5c6..f660cad 100644
--- a/src/codegen.cpp
+++ b/src/codegen.cpp
@@ -4675,7 +4675,7 @@ static void emit_function(jl_lambda_info_t *lam, jl_llvm_functions_t *declaratio
     ctx.dbuilder = &dbuilder;
 #ifdef LLVM37
     DIFile *topfile = NULL;
-    DISubprogram *SP;
+    DISubprogram *SP = NULL;
     DICompileUnit *CU;
 #else
     DIFile topfile;
```

The non-LLVM37 one shouldn't be an issue since it is always default initialized.
