### ISSUE TITLE
Can't compile Julia on aarch64-linux

### ISSUE THREAD

**Issue by giordano** [JuliaLang/julia#61824]
This happens on multiple systems, where I used GCC 11 and 13:
```
    LINK usr/lib/libjulia-internal.so.1.14.0
    LINK usr/lib/libjulia-internal.so.1.14
    LINK usr/lib/libjulia-internal.so
    LINK usr/lib/libjulia-codegen.so.1.14.0
/usr/bin/ld: ./jitlayers.o: in function `std::__atomic_base<unsigned long>::operator--()':
/usr/include/c++/11/bits/atomic_base.h:393: undefined reference to `__aarch64_ldadd8_acq_rel'
/usr/bin/ld: ./jitlayers.o: in function `std::__atomic_base<unsigned long>::operator++()':
/usr/include/c++/11/bits/atomic_base.h:385: undefined reference to `__aarch64_ldadd8_acq_rel'
/usr/bin/ld: ./jitlayers.o: in function `std::__atomic_base<unsigned long>::operator--()':
/usr/include/c++/11/bits/atomic_base.h:393: undefined reference to `__aarch64_ldadd8_acq_rel'
/usr/bin/ld: /usr/include/c++/11/bits/atomic_base.h:393: undefined reference to `__aarch64_ldadd8_acq_rel'
/usr/bin/ld: /usr/include/c++/11/bits/atomic_base.h:393: undefined reference to `__aarch64_ldadd8_acq_rel'
/usr/bin/ld: ./jitlayers.o:/usr/include/c++/11/bits/atomic_base.h:393: more undefined references to `__aarch64_ldadd8_acq_rel' follow
/usr/bin/ld: ./jitlayers.o: in function `std::__atomic_base<unsigned long>::fetch_add(unsigned long, std::memory_order)':
/usr/include/c++/11/bits/atomic_base.h:618: undefined reference to `__aarch64_ldadd8_relax'
/usr/bin/ld: ./jitlayers.o: in function `std::__atomic_base<unsigned long>::operator--()':
/usr/include/c++/11/bits/atomic_base.h:393: undefined reference to `__aarch64_ldadd8_acq_rel'
/usr/bin/ld: /usr/include/c++/11/bits/atomic_base.h:393: undefined reference to `__aarch64_ldadd8_acq_rel'
/usr/bin/ld: /usr/include/c++/11/bits/atomic_base.h:393: undefined reference to `__aarch64_ldadd8_acq_rel'
/usr/bin/ld: /usr/include/c++/11/bits/atomic_base.h:393: undefined reference to `__aarch64_ldadd8_acq_rel'
/usr/bin/ld: /usr/include/c++/11/bits/atomic_base.h:393: undefined reference to `__aarch64_ldadd8_acq_rel'
/usr/bin/ld: ./jitlayers.o:/usr/include/c++/11/bits/atomic_base.h:393: more undefined references to `__aarch64_ldadd8_acq_rel' follow
/usr/bin/ld: ./jitlayers.o: in function `std::__atomic_base<unsigned long>::fetch_add(unsigned long, std::memory_order)':
/usr/include/c++/11/bits/atomic_base.h:618: undefined reference to `__aarch64_ldadd8_relax'
/usr/bin/ld: /usr/include/c++/11/bits/atomic_base.h:618: undefined reference to `__aarch64_ldadd8_relax'
/usr/bin/ld: ./jitlayers.o: in function `std::__atomic_base<unsigned long>::operator--()':
/usr/include/c++/11/bits/atomic_base.h:393: undefined reference to `__aarch64_ldadd8_acq_rel'
/usr/bin/ld: /usr/include/c++/11/bits/atomic_base.h:393: undefined reference to `__aarch64_ldadd8_acq_rel'
/usr/bin/ld: /usr/include/c++/11/bits/atomic_base.h:393: undefined reference to `__aarch64_ldadd8_acq_rel'
/usr/bin/ld: /usr/include/c++/11/bits/atomic_base.h:393: undefined reference to `__aarch64_ldadd8_acq_rel'
[...]
```

**Comment by giordano** [comment]
Bisected to #61652
```
d19eac062f4083e8cb4777323904cb87fab35200 is the first bad commit
commit d19eac062f4083e8cb4777323904cb87fab35200
Author: Cody Tapscott <84105208+topolarity@users.noreply.github.com>
Date:   Mon Apr 27 19:07:51 2026 -0400

    Base.Linking: Link C runtime libraries by default (#61652)

    Linux / Windows (glibc) equivalent to
    https://github.com/JuliaLang/julia/pull/61633.

    This allows us to turn on `-z def` when linking the sysimage /
    pkgimages. I tried to emulate a "standard" link via `gcc` as much as
    possible. This change will also be useful for linking shared libraries /
    executables generated by `--trim` / `JuliaC.jl`

    Also fixes the `refresh_checksums.mk` bug that @giordano ran into in
    https://github.com/JuliaLang/julia/pull/61460.

 Makefile                                         | 34 +++++++--
 base/linking.jl                                  | 75 ++++++++++++------
 contrib/refresh_checksums.mk                     |  8 +-
 deps/checksums/compilersupportlibraries          | 72 +++++++++---------
 deps/csl.mk                                      | 97 ++++++++++++++++++++----
 stdlib/CompilerSupportLibraries_jll/Project.toml |  2 +-
 6 files changed, 210 insertions(+), 78 deletions(-)
```
CC @topolarity.

**Comment by giordano** [comment]
Compiling with `make CXXFLAGS="-mno-outline-atomics" CFLAGS="-mno-outline-atomics"` does the trick for me.

**Comment by giordano** [comment]
To further add more information about this issue, [`-mno-outline-atomics` is needed only when targeting the baseline `armv8.0a`](https://gcc.gnu.org/onlinedocs/gcc/AArch64-Options.html#index-moutline-atomics), which is the default when compiling for aarch64 (also note that [the flag was added in GCC 10](https://gcc.gnu.org/gcc-10/changes.html), in CI we build with GCC 9, which would explain why we don't observe this issue in CI).  Therefore, when targeting an ISA higher than armv8.0a, another workaround is to set `MCPU` appropriately.  We actually default `MCPU` to `native` when `JULIA_CPU_TARGET` is not set:  https://github.com/JuliaLang/julia/blob/690a68d60bd237451829310bce4bd0f21f8f44e7/Make.inc#L1101-L1105 but I was testing https://github.com/JuliaLang/cpufeatures/pull/49 so I had to set `JULIA_CPU_TARGET`.  For my use case (local testing),
```sh
make -j MCPU=native
```
would be another effective workaround, but in general `MCPU=native` defeats the purpose of setting `JULIA_CPU_TARGET="generic;..."` to have a generic build.

With @gbaraldi we were discussing offline the possibility of raising the baseline supported ISA on aarch64 to armv8.1a, but this would mean to cut out support for devices like Raspberry Pi 4 and Nvidia Jetson Nano, not sure we are ready for that.

**Comment by topolarity** [comment]
@giordano Can you share the full link invocation? 

What does your `libgcc.a` from BB have? `nm ./usr/lib/libgcc.a | grep __aarch64_ldadd8_acq_rel`

**Comment by giordano** [comment]
> @giordano Can you share the full link invocation?

```console
$ export JULIA_CPU_TARGET="generic;cortex-a57;thunderx2t99;carmel,clone_all;apple-m1,base(3);neoverse-512tvb,-rand,-fpac,base(3)"
$ make VERBOSE=1
[...]
 g++ -shared  -O3 -DJL_SYSTEM_IMAGE_PATH='"../lib/julia/sys.so"' -DJL_LIBJULIA_SONAME='"libjulia.so.1.14"' -D_GNU_SOURCE -I. -I/data/cceamgi/repo/julia/src -I/data/cceamgi/repo/julia/src/flisp -I/data/cceamgi/repo/julia/src/support -I/data/cceamgi/repo/julia/usr/include -I/data/cceamgi/repo/julia/usr/include -I/data/cceamgi/repo/julia/deps/valgrind -Wall -Wno-strict-aliasing -fno-omit-frame-pointer -fvisibility=hidden -fno-common -Wno-comment -Wpointer-arith -Wundef -DJL_BUILD_ARCH='"aarch64"' -DJL_BUILD_UNAME='"Linux"' -I/data/cceamgi/repo/julia/usr/include -DLLVM_SHLIB -ggdb2 -falign-functions -Wno-unused-result -Wno-stringop-overflow -Wno-stringop-overread -Wno-maybe-uninitialized  -pipe -fPIC -fno-rtti -std=c++17 -Wformat -Wformat-security -fno-strict-aliasing  -fno-gnu-unique -pedantic -DUSE_NVTX -ffunction-sections -fdata-sections -D_FILE_OFFSET_BITS=64  ./codegen.o ./jitlayers.o ./aotcompile.o ./debuginfo.o ./disasm.o ./llvm-simdloop.o ./llvm-pass-helpers.o ./llvm-ptls.o ./llvm-propagate-addrspaces.o ./llvm-multiversioning.o ./llvm-alloc-opt.o ./llvm-alloc-helpers.o ./cgmemmgr.o ./llvm-remove-addrspaces.o ./llvm-remove-ni.o ./llvm-julia-licm.o ./llvm-demote-float16.o ./llvm-cpufeatures.o ./llvm-expand-atomic-modify.o ./pipeline.o ./llvm_api.o ./llvm-final-gc-lowering.o ./llvm-late-gc-lowering.o ./llvm-gc-invariant-verifier.o ./llvm-final-gc-lowering-stock.o -Wl,-rpath,'$ORIGIN' -Wl,-z,origin -Wl,--enable-new-dtags -o /data/cceamgi/repo/julia/usr/lib/libjulia-codegen.so.1.14.0 -Wl,-z,relro -Wl,--gc-sections -Wl,-Bdynamic -Wl,-no-undefined    -Wl,-Bsymbolic-functions -Wl,--enable-new-dtags -Wl,-z,noexecstack -L/data/cceamgi/repo/julia/usr/lib -L/data/cceamgi/repo/julia/usr/lib -lunwind -L/data/cceamgi/repo/julia/usr/lib  -lLLVM-21jl -lz -lzstd -Wl,--no-as-needed -ldl -lrt -lpthread -latomic -Wl,--export-dynamic,--as-needed,--no-whole-archive -Wl,--version-script=/data/cceamgi/repo/julia/src/julia.expmap   -ljulia -ljulia-internal   -Wl,-soname=libjulia-codegen.so.1.14
```

> What does your `libgcc.a` from BB have? `nm ./usr/lib/libgcc.a | grep __aarch64_ldadd8_acq_rel`

In CompilerSupportLibraries_jll we don't have `libgcc.a`.  But the `libgcc.a` inside BinaryBuilder toolchain does have the symbol:
```console
julia> using BinaryBuilderBase

julia> BinaryBuilderBase.runshell(Platform("aarch64", "linux"); preferred_gcc_version=v"15");
sandbox:${WORKSPACE} # nm /opt/${target}/lib/gcc/${target}/15.2.0/libgcc.a | grep __aarch64_ldadd8_acq_rel
0000000000000000 T __aarch64_ldadd8_acq_rel
```

**Comment by gbaraldi** [comment]
Shouldn't the gcc just use it's own libgcc.a instead then?

**Comment by giordano** [comment]
Wait, I got lost before, the file `libgcc.a` is there inside julia's `usr/lib` and it does have the symbol:
```console
$ nm ./usr/lib/libgcc.a | grep __aarch64_ldadd8_acq_rel
0000000000000000 T __aarch64_ldadd8_acq_rel
```
But we're missing a `-lgcc` in the compiler invocation?

**Comment by gbaraldi** [comment]
That's possible

**Comment by topolarity** [comment]
> But we're missing a `-lgcc` in the compiler invocation?

Ah I thought that `-shared` would add that automatically, but it looks like that only covers `-lgcc_s` not `-lgcc`

**Comment by topolarity** [comment]
Oh the linker script that does that is deleted in the Yggdrasil recipe: https://github.com/JuliaPackaging/Yggdrasil/blob/270cae687fc8b161e05aae0cd4b462060d94660e/C/CompilerSupportLibraries/common.jl#L119

and then the symlink I added is only a partial replacement: https://github.com/JuliaLang/julia/blob/cad4314e3be8e9e3aa6aa74551941854f4c4c2c3/deps/csl.mk#L127-L128
