### PR TITLE
Backports release 1.5.3

### LINKED ISSUE #37880: Codegen bug with Base.lshr_int intrinsic
Ref: https://discourse.julialang.org/t/failure-with-lshr-int-intrinsic-for-on-uint256-type/47738/4
@simeonschaub suggested this repro which "looks like it’s an LLVM bug":
```
julia> primitive type UInt256 256 end

julia> x = reinterpret(UInt256, rand(UInt128, 2))[]
UInt256(0x48805fdfb72d71fadaf8daa563cf816383f755d9d9e70d703fa348f556c717ad)

julia> f(x) = Base.lshr_int(x, 0x8)
f (generic function with 1 method)

julia> @code_llvm optimize=false f(x)
;  @ REPL[22]:1 within `f'
define void @julia_f_392(i256* noalias nocapture sret %0, i256 %1) {
top:
  %2 = call {}*** @julia.ptls_states()
  %3 = bitcast {}*** %2 to {}**
  %4 = getelementptr inbounds {}*, {}** %3, i64 4
  %5 = bitcast {}** %4 to i64**
  %6 = load i64*, i64** %5
  %7 = lshr i256 %1, 8
  %8 = select i1 true, i256 0, i256 %7
  store i256 %8, i256* %0, align 8
  ret void
}

julia> @code_llvm optimize=true f(x)
;  @ REPL[22]:1 within `f'
define void @julia_f_394(i256* noalias nocapture sret %0, i256 %1) {
top:
  store i256 0, i256* %0, align 8
  ret void
}
```

### PR DESCRIPTION
**Pull request by KristofferC**
Backported PRs:
- [x] #36396 - fix showing methods with unicode gensymed variable names
- [x] #37236 - Add INNO_ARGS makefile var for signtool
- [x] #37613 - increase `RELOC_TAG_OFFSET` to handle larger system images
- [x] #37562 - Revert "Improve typesubtract for tuples (#35600)"
- [x] #37407 - Bump libuv to latest commit
- [x] #37594 - dump: ensure Array eltype layout is initialized early
- [x] #36821 - Fix function call to rec_backtrace_ctx when using USE_SYSTEM_LIBUNWIND=1
- [x] #37002 - win32: fix in_stackwalk mutex
- [x] #37101 - make Profile more thread/signal-safe
- [x] #37769 - Fix `getfield_tfunc` for `PartialStruct` with `Vararg
- [x] #38049 - Make `static_show()` print valid identifiers

Need manual backport:
- [ ] #37557 - Fix === and objectid of object with potentially undef inline immutable field
- [ ] #37645 - fix fields description of Module type
- [ ] #37891 - fix #37880, overflow in shift amount range check in codegen

Contains multiple commits, manual intervention needed:
- [ ] #37243 - code coverage fixes

### CODE REVIEW

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/julia/pull/37557 introduced a bug that is fixed by https://github.com/JuliaLang/julia/pull/37896

**Comment by Sacha0** [comment]
@KristofferC, I hope you don't mind: I took the liberty of pushing the patches we carry for

 #37594 - dump: ensure Array eltype layout is initialized early
 #37101 - make Profile more thread/signal-safe
 #36821 - Fix function call to rec_backtrace_ctx when using USE_SYSTEM_LIBUNWIND=1

on Julia 1.5.2 and checked off / added those to your list of manual backports at top :). (Those patches have been exercised by our team for a few weeks each now.)

**Comment by Sacha0** [comment]
Hm, would #38049 be a backport candidate once it merges, what with fixing precompilation failures?

**Comment by KristofferC** [comment]
Seems like a nice bug fix, so makes sense to me. Usually it is good to have PRs be on master for a while to shake out anything egregiously wrong but that should be pretty harmless and easy to test.

**Comment by KristofferC** [comment]
@Sacha0, seems like Windows is not happy with one of the backports?

**Comment by martinholters** [comment]
Include #37769?

**Comment by dkarrasch** [comment]
Also include #38002?

**Comment by Sacha0** [comment]
> @Sacha0, seems like Windows is not happy with one of the backports?

Hm, I don't think we have anyone running these patches on Windows, so perhaps that's not entirely surprising 😄. I suspect the patch for #38048; having a look at the logs now.

**Comment by Sacha0** [comment]
Yes, it looks like #38048 introduces the failure on Windows. Amusingly the failure is the Windows-equivalent of #36821:
```
In file included from /cygdrive/c/buildbot/worker/package_win64/build/src/signal-handling.c:117:
/cygdrive/c/buildbot/worker/package_win64/build/src/signals-win.c:354:36: error: too few arguments to function 'rec_backtrace_ctx'
  354 |                     bt_size_cur += rec_backtrace_ctx((jl_bt_element_t*)bt_data_prof + bt_size_cur,
      |                                    ^~~~~~~~~~~~~~~~~
```
i.e. the rec_backtrace_ctx calls introduced by #38048 need the trailing argument that #36821 adds to a call in signals-mach.c.

**Comment by Sacha0** [comment]
I've pushed a commit that should sort out the error identified above. I'm not confident that fix will sort windows out altogether, but let's ask the buildbot 🤞 :).

**Comment by Sacha0** [comment]
It looks like win32 failed in a new and exciting way also related to #38048 (particularly its removal of jl_trygetUnwindInfo). Having a look now :).

**Comment by Sacha0** [comment]
That last push seems to have fixed the package_ failures, but surfaced another new and exciting failure in tester_win32. I suspect that fixing the latter requires adding https://github.com/JuliaLang/julia/pull/37002 to the patch. I will give that a whirl tomorrow.

**Comment by Sacha0** [comment]
I think I've managed to backport #37002 with #37101 on top, by which I mean the result appears to function locally. Let's see what the buildbot thinks? :)

**Comment by Sacha0** [comment]
(I should add that #37002 should obviate the patch from #36821, so I dropped the latter.)

**Comment by Sacha0** [comment]
The package_linuxaarch64 failure was a timeout, and the logs look otherwise clean. So we seem to be in good shape. I'll stop messing with your branch now @KristofferC 😄.

**Comment by KristofferC** [comment]
@nanosoldier `runtests(ALL, vs = ":release-1.5")`

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-1.5")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/38122#issuecomment-716184360):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`git fetch --all --quiet`, ProcessExited(128)) [128]

```
Logs and partial data can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/d5bc1402ea97ea3382b1e680239277103914fd98/benchmark/by_hash/3de1115_vs_5905ede/report.md)
cc @christopher-dG

**Comment by christopher-dG** [comment]
Can someone try that again and see if it happens a second time? It might just be a bit of GitHub downtime if not.

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-1.5")`

**Comment by nanosoldier** [comment]
Something went wrong when running [your job](https://github.com/JuliaLang/julia/pull/38122#issuecomment-716197938):
```
NanosoldierError: failed to run benchmarks against primary commit: failed process: Process(`git fetch --all --quiet`, ProcessExited(128)) [128]

```
Logs and partial data can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/400b79fd63b2b2bac0f1a00e618659d64406c47e/benchmark/by_hash/3de1115_vs_5905ede/report.md)
cc @christopher-dG

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/38122#issuecomment-716184284) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/55989a1ca4368851199fe95e87a2a88d48df5df2/pkgeval/by_hash/bb83a29_vs_5905ede/report.md). cc @maleadt

**Comment by christopher-dG** [comment]
Welp, I'll see what's going on with benchmarks tomororw.

**Comment by christopher-dG** [comment]
Benchmarks should hopefully work again, Nanosoldier assumes that BaseBenchmarks is `dev`ed with a Git repo available rather than `add`ed.

**Comment by NHDaly** [comment]
> Hm, would #38049 be a backport candidate once it merges, what with fixing precompilation failures?


> Seems like a nice bug fix, so makes sense to me. Usually it is good to have PRs be on master for a while to shake out anything egregiously wrong but that should be pretty harmless and easy to test.


It sounds like we're planning to backport this? I've opened a PR against this branch, here:
https://github.com/JuliaLang/julia/pull/38183

**Comment by KristofferC** [comment]
@nanosoldier `runtests(["Autologistic", "BlobTracking", "Cambrian", "Catalyst", "ChainRules", "ClimateERA", "CodeTransformation", "DiffEqOperators", "FlashWeave", "ImageDistances", "Oscar", "RiskAdjustedLinearizations", "Sched", "StochasticDelayDiffEq", "Tar", "Thorn", "TimeToLive", "Turmeric"], vs = ":release-1.5")`

**Comment by KristofferC** [comment]
@nanosoldier `runbenchmarks(ALL, vs = ":release-1.5")`

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/julia/pull/38122#issuecomment-716752947) has completed - possible new issues were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/95aff205184716b4cc7fd799ab4d55a13ba33dfc/pkgeval/by_hash/bb83a29_vs_5905ede/report.md). cc @maleadt

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/38122#issuecomment-716753040) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/NanosoldierReports/blob/3c5300db710849526d8c8ed1537a111ebb3bc1b4/benchmark/by_hash/3de1115_vs_5905ede/report.md). cc @christopher-dG

**Comment by KristofferC** [comment]
https://github.com/perrutquist/CodeTransformation.jl segfaults but that one heavily uses nternals so not sure we can do much about that.

**Comment by Sacha0** [comment]
From a brief review of this thread, it seems like this pull request, and ergo 1.5.3, is ready to go? Is merge etc waiting on anything at this point? :)

**Comment by KristofferC** [comment]
I think this should be good to go from my pov as well.

**Comment by dkarrasch** [comment]
What about https://github.com/JuliaLang/julia/pull/38122#issuecomment-714437245? It fixes something that got broken in v1.5.0.

**Comment by racinmat** [comment]
Hi, is there a chance #37243 will make it to some 1.5.* release? It seems it didn't make it to 1.5.2 nor 1.5.3.
