### PR TITLE
Fix the example for MSVC in the Embedding Julia documentation

### PR DESCRIPTION
**Pull request by Taaitaaiger**
The current example for embedding Julia with MSVC fails to compile, this pull request provides a working example using code from [`julia_headers.hpp` from `CxxWrap`](https://github.com/JuliaInterop/libcxxwrap-julia/blob/main/include/jlcxx/julia_headers.hpp)

### CODE REVIEW

**Comment by ViralBShah** [comment]
This feels a bit fussy. Does this mean we need to something within Julia to make it nicer?

**Comment by Taaitaaiger** [comment]
Do you mean nicer in the sense that the additional includes and using C++ wouldn't be necessary? That would definitely be better IMO, but I'm not sure if that's possible because Julia uses features like `_Atomic` that MSVC doesn't support.

**Comment by ViralBShah** [comment]
Ok. I suppose having a working example is better in any case. @vtjnash can you review?

**Review by vtjnash — CHANGES_REQUESTED** [review]
This change seems to make no sense to me. I think it is all old support content for headers that we deleted in v1.8?

**Comment by Taaitaaiger** [comment]
The issue is quite old, actually.

The example that's currently available already failed to build with MSVC using Julia 1.5: https://github.com/JuliaLang/julia/issues/37957
Users of libcxxwrap have run into this problem: https://github.com/JuliaLang/julia/issues/34201
Eventually @toivoh provided a working solution here: https://github.com/JuliaLang/julia/issues/39595

I decided to provide a new example based on what CxxWrap does because that example works.

**Comment by Taaitaaiger** [comment]
This PR doesn't affect any code but only changes some documentation. I think you might be confused with this recent PR I've made recently: https://github.com/JuliaLang/julia/pull/44842

**Comment by vtjnash** [comment]
Closing as I believe this does not apply to master, only old versions. Please let me know if that is wrong and we will try to fix master not to need this.

**Comment by barche** [comment]
I was just checking this, it's true that the original "No Target Architecture" error appears only in Julia 1.6 and 1.7, but using the latest nightly there still is an error that is fixed by adding these lines. The error I get when removing the workaround from CxxWrap is:

```
C:\hostedtoolcache\windows\julia\nightly\x64\include\julia\ios.h(113,33): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\a\libcxxwrap-julia\libcxxwrap-julia\build\cxxwrap_julia.vcxproj]
C:\hostedtoolcache\windows\julia\nightly\x64\include\julia\ios.h(113,22): error C2146: syntax error: missing ';' before identifier 'ios_fillbuf' [D:\a\libcxxwrap-julia\libcxxwrap-julia\build\cxxwrap_julia.vcxproj]
```

With the workaround, it compiles against nightly. Presumably 1.8 has the same issue, but there MSVC doesn't work because of #44842.

**Comment by vtjnash** [comment]
ah, I suppose we could add this code (from uv/win.h) to src/support/dtypes.h to make sure that definition is available in standalone mode
```c
26  #if !defined(_SSIZE_T_) && !defined(_SSIZE_T_DEFINED)
  1 typedef intptr_t ssize_t;
  2 # define SSIZE_MAX INTPTR_MAX
  3 # define _SSIZE_T_
  4 # define _SSIZE_T_DEFINED
  5 #endif
```

**Comment by Taaitaaiger** [comment]
Thanks for checking, @barche, and providing a better PR!
