### ISSUE TITLE
`MethodTable` serialization broken by PR #58131

### ISSUE THREAD

**Issue by christiangnrd** [JuliaLang/julia#58557]
Seems like https://github.com/JuliaLang/julia/pull/58131 broke `MethodTable` serialization:

```julia-repl
ChrichriMBP:~$ j +nightly --banner=short
  o  | Version 1.13.0-DEV.647 (2025-05-28)
 o o | Commit 1735d8f03c9 (0 days old master)
julia> using Serialization; Base.Experimental.@MethodTable mt; serialize(devnull, mt)
ERROR: FieldError: type MethodCache has no field `name`, available fields: `leafcache`, `cache`, ``, ``
Stacktrace:
 [1] getproperty
   @ ./Base_compiler.jl:57 [inlined]
 [2] serialize(s::Serializer{Base.DevNull}, mc::Core.MethodCache)
   @ Serialization ~/.julia/juliaup/julia-nightly/share/julia/stdlib/v1.13/Serialization/src/Serialization.jl:478
 [3] serialize(s::Serializer{Base.DevNull}, mt::Core.MethodTable)
   @ Serialization ~/.julia/juliaup/julia-nightly/share/julia/stdlib/v1.13/Serialization/src/Serialization.jl:472
 [4] serialize(s::Base.DevNull, x::Core.MethodTable)
   @ Serialization ~/.julia/juliaup/julia-nightly/share/julia/stdlib/v1.13/Serialization/src/Serialization.jl:813
 [5] top-level scope
   @ REPL[1]:1
```

CC @vtjnash
