### ISSUE TITLE
Recent build failure with LLVM 3.5.0

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#11556]
I see this build failure on Fedora 21 with LLVM 3.5.0. Looks like it's been introduced in the last few days:
```
 gcc -march=x86-64 -m64  "-DJL_SYSTEM_IMAGE_PATH=\"../lib64/julia/sys.ji\"" -DSYSTEM_LLVM -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -std=gnu99 -pipe -fPIC -fno-strict-aliasing -D_FILE_OFFSET_BITS=64 -DCOPY_STACKS -O3 -ggdb3 -falign-functions -momit-leaf-frame-pointer -D_GNU_SOURCE -Iflisp -Isupport -I/usr/include -I/builddir/build/BUILD/julia/build/usr/include -I/builddir/build/BUILD/julia/build/usr/include -DLIBRARY_EXPORTS -I. -I/builddir/build/BUILD/julia/deps/valgrind -Wall -Wno-strict-aliasing -fno-omit-frame-pointer -fvisibility=hidden -fno-common -DNDEBUG -c module.c -o module.o
 g++ -march=x86-64 -m64 -I/usr/include  -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3 -fomit-frame-pointer -std=c++11 -fvisibility-inlines-hidden -fno-exceptions -fPIC -Woverloaded-virtual -ffunction-sections -fdata-sections -Wcast-qual  "-DJL_SYSTEM_IMAGE_PATH=\"../lib64/julia/sys.ji\"" -DSYSTEM_LLVM -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -pipe -fPIC -fno-rtti -O3 -ggdb3 -falign-functions -momit-leaf-frame-pointer -D_GNU_SOURCE -Iflisp -Isupport -I/usr/include -I/builddir/build/BUILD/julia/build/usr/include -I/builddir/build/BUILD/julia/build/usr/include -DLIBRARY_EXPORTS -I. -I/builddir/build/BUILD/julia/deps/valgrind -Wall -Wno-strict-aliasing -fno-omit-frame-pointer -fvisibility=hidden -fno-common -c codegen.cpp -o codegen.o
 g++ -march=x86-64 -m64 -I/usr/include  -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3 -fomit-frame-pointer -std=c++11 -fvisibility-inlines-hidden -fno-exceptions -fPIC -Woverloaded-virtual -ffunction-sections -fdata-sections -Wcast-qual  "-DJL_SYSTEM_IMAGE_PATH=\"../lib64/julia/sys.ji\"" -DSYSTEM_LLVM -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -pipe -fPIC -fno-rtti -O3 -ggdb3 -falign-functions -momit-leaf-frame-pointer -D_GNU_SOURCE -Iflisp -Isupport -I/usr/include -I/builddir/build/BUILD/julia/build/usr/include -I/builddir/build/BUILD/julia/build/usr/include -DLIBRARY_EXPORTS -I. -I/builddir/build/BUILD/julia/deps/valgrind -Wall -Wno-strict-aliasing -fno-omit-frame-pointer -fvisibility=hidden -fno-common -c disasm.cpp -o disasm.o
 g++ -march=x86-64 -m64 -I/usr/include  -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3 -fomit-frame-pointer -std=c++11 -fvisibility-inlines-hidden -fno-exceptions -fPIC -Woverloaded-virtual -ffunction-sections -fdata-sections -Wcast-qual  "-DJL_SYSTEM_IMAGE_PATH=\"../lib64/julia/sys.ji\"" -DSYSTEM_LLVM -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -pipe -fPIC -fno-rtti -O3 -ggdb3 -falign-functions -momit-leaf-frame-pointer -D_GNU_SOURCE -Iflisp -Isupport -I/usr/include -I/builddir/build/BUILD/julia/build/usr/include -I/builddir/build/BUILD/julia/build/usr/include -DLIBRARY_EXPORTS -I. -I/builddir/build/BUILD/julia/deps/valgrind -Wall -Wno-strict-aliasing -fno-omit-frame-pointer -fvisibility=hidden -fno-common -c debuginfo.cpp -o debuginfo.o
debuginfo.cpp: In function 'void jl_getFunctionInfo(const char**, size_t*, const char**, size_t, int*, int)':
debuginfo.cpp:735:33: error: 'struct ObjectInfo' has no member named 'slide'
         pointer -= (*it).second.slide;
                                 ^
Makefile:71: recipe for target 'debuginfo.o' failed
make[1]: *** [debuginfo.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/builddir/build/BUILD/julia/src'
Makefile:58: recipe for target 'julia-src-release' failed
make: *** [julia-src-release] Error 2
```
https://copr-be.cloud.fedoraproject.org/results/nalimilan/julia-nightlies/fedora-21-x86_64/julia-0.4.0-0.20150602.fc21/

**Comment by crayxt** [comment]
Introduced by https://github.com/JuliaLang/julia/commit/8d8638726473b97b2ca4b9e13a54e897fe06843a I suppose

**Comment by crayxt** [comment]
@nalimilan What about builds with older LLVM?

**Comment by nalimilan** [comment]
Indeed, it also fails with LLVM 3.4: https://copr-be.cloud.fedoraproject.org/results/nalimilan/julia-nightlies/fedora-20-x86_64/julia-0.4.0-0.20150602.fc21/build.log.gz

**Comment by Keno** [comment]
My apologies, I don't routinely test with LLVM 3.5. Will fix.

**Comment by nalimilan** [comment]
@Keno Any chance you look at it? Thanks!

**Comment by nalimilan** [comment]
(Sorry, I missed it since GitHub does not send notification e-mails for commits...) I can confirm it fixed the build issue, though crashes happen now.
