### ISSUE TITLE
Julia 0.5 fails to compile on Ubuntu (16.04) with Intel MKL

### ISSUE THREAD

**Issue by GravityAssisted** [JuliaLang/julia#18170]
I cloned a new Julia-0.5 GIT repository and modified the `Make.user` as follows:

```
USEICC = 1
USEIFC = 1
USE_INTEL_MKL = 1
USE_INTEL_MKL_FFT = 1
USE_INTEL_LIBM = 1
```

Running `make` results in LLVM errors. Julia 0.5 compiles fine if I don’t use the `Make.user` file. I using Intel Compiler version 15.03 with System: Linux (x86_64-linux-gnu), CPU: Intel(R) Xeon(R) CPU E5-2630 v2 @ 2.60GHz, OS:Ubuntu 16.04 LTS.

Is this a known issue and is there a way around this ?

The error is as follows:

```
llvm[3]: Compiling ScaledNumber.cpp for Release build
icpc: command line warning #10006: ignoring unknown option '-Wcovered-switch-default'
llvm[3]: Compiling SearchForAddressOfSpecialSymbol.cpp for Release build
icpc: command line warning #10006: ignoring unknown option '-Wcovered-switch-default'
llvm[3]: Compiling Signals.cpp for Release build
icpc: command line warning #10006: ignoring unknown option '-Wcovered-switch-default'
In file included from /home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Signals.cpp(30):
/usr/include/c++/5/bits/stl_iterator_base_types.h(154): error: name followed by "::" must be a class or namespace name
        typedef typename _Iterator::iterator_category iterator_category;
                         ^
In file included from /home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Signals.cpp(30):
          detected during:
In file included from /home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Signals.cpp(30):
            instantiation of class "std::__iterator_traits<_Iterator, void> [with _Iterator=int]" at line 163
In file included from /home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Signals.cpp(30):
            instantiation of class "std::iterator_traits<_Iterator> [with _Iterator=int]" at line 358 of "/home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Unix/Signals.inc"
In file included from /home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Signals.cpp(30):

In file included from /home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Signals.cpp(30):
/usr/include/c++/5/bits/stl_iterator_base_types.h(155): error: name followed by "::" must be a class or namespace name
        typedef typename _Iterator::value_type        value_type;
                         ^
In file included from /home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Signals.cpp(30):
          detected during:
In file included from /home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Signals.cpp(30):
            instantiation of class "std::__iterator_traits<_Iterator, void> [with _Iterator=int]" at line 163
In file included from /home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Signals.cpp(30):
            instantiation of class "std::iterator_traits<_Iterator> [with _Iterator=int]" at line 358 of "/home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Unix/Signals.inc"
In file included from /home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Signals.cpp(30):

In file included from /home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Signals.cpp(30):
/usr/include/c++/5/bits/stl_iterator_base_types.h(156): error: name followed by "::" must be a class or namespace name
        typedef typename _Iterator::difference_type   difference_type;
                         ^
In file included from /home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Signals.cpp(30):
          detected during:
In file included from /home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Signals.cpp(30):
            instantiation of class "std::__iterator_traits<_Iterator, void> [with _Iterator=int]" at line 163
In file included from /home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Signals.cpp(30):
            instantiation of class "std::iterator_traits<_Iterator> [with _Iterator=int]" at line 358 of "/home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Unix/Signals.inc"
In file included from /home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Signals.cpp(30):

In file included from /home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Signals.cpp(30):
/usr/include/c++/5/bits/stl_iterator_base_types.h(157): error: name followed by "::" must be a class or namespace name
        typedef typename _Iterator::pointer           pointer;
                         ^
In file included from /home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Signals.cpp(30):
          detected during:
In file included from /home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Signals.cpp(30):
            instantiation of class "std::__iterator_traits<_Iterator, void> [with _Iterator=int]" at line 163
In file included from /home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Signals.cpp(30):
            instantiation of class "std::iterator_traits<_Iterator> [with _Iterator=int]" at line 358 of "/home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Unix/Signals.inc"
In file included from /home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Signals.cpp(30):

In file included from /home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Signals.cpp(30):
/usr/include/c++/5/bits/stl_iterator_base_types.h(158): error: name followed by "::" must be a class or namespace name
        typedef typename _Iterator::reference         reference;
                         ^
In file included from /home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Signals.cpp(30):
          detected during:
In file included from /home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Signals.cpp(30):
            instantiation of class "std::__iterator_traits<_Iterator, void> [with _Iterator=int]" at line 163
In file included from /home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Signals.cpp(30):
            instantiation of class "std::iterator_traits<_Iterator> [with _Iterator=int]" at line 358 of "/home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Unix/Signals.inc"
In file included from /home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Signals.cpp(30):

compilation aborted for /home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/lib/Support/Signals.cpp (code 2)
/home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/Makefile.rules:1521: recipe for target '/home/arora/src/julia_0.5/intel/julia/deps/build/llvm-3.7.1/build_Release/lib/Support/Release/Signals.o' failed
make[3]: *** [/home/arora/src/julia_0.5/intel/julia/deps/build/llvm-3.7.1/build_Release/lib/Support/Release/Signals.o] Error 1
/home/arora/src/julia_0.5/intel/julia/deps/srccache/llvm-3.7.1/Makefile.rules:880: recipe for target 'all' failed
make[2]: *** [all] Error 1
/home/arora/src/julia_0.5/intel/julia/deps/llvm.mk:500: recipe for target 'build/llvm-3.7.1/build_Release/Release/lib/libLLVMCodeGen.a' failed
make[1]: *** [build/llvm-3.7.1/build_Release/Release/lib/libLLVMCodeGen.a] Error 2
Makefile:81: recipe for target 'julia-deps' failed
make: *** [julia-deps] Error 2
```

thanks all!

**Comment by GravityAssisted** [comment]
The error occurs when ```icpc``` tries to compile ``` Signals.cpp ```.
Btw: ```icpc -v``` gives the follows:
```
icpc version 15.0.3 (gcc version 5.0.0 compatibility)
```

**Comment by yuyichao** [comment]
What's the GCC version on your system?

**Comment by GravityAssisted** [comment]
@yuyichao its``` gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2)```

**Comment by tkelman** [comment]
https://software.intel.com/en-us/forums/intel-c-compiler/topic/565143
> this problem (DPD200365668) marking it as fixed in the 2016.2.181 release

**Comment by ViralBShah** [comment]
Cc @kpamnany @lkuper

**Comment by GravityAssisted** [comment]
Thanks.. I will upgrade my Intel suite or downgrade gcc.
Nitin

**Comment by tkelman** [comment]
Closing this assuming it was fixed upstream, but leave a comment and we'll reopen if not. Doc notes on this also welcome.
