### PR TITLE
Only emit incoming values for the phi when needed

### LINKED ISSUE #37265: Segfault instead of throwing UndefVarError — includes rr trace
The test case from [this discourse question](https://discourse.julialang.org/t/function-closures-and-ifelse-with-unexpected-behaviour/45694) leads to a segfault after the local function definitions are changed to either anonymous functions (which I tried locally) or local assignment of different functions (as shown in the third reply).

~~A later reply identified just changing `@error` to `error()` in the function definition avoids the segfault.~~ The `else` branch doesn't define `showcase()`, so the later call should result in an `UndefVarError` being thrown. (The earlier observation that `error()` works is because that cases the function to throw an actual error and exit the function before the call following the if-else block is called.)

I've tried out Julia v1.5's new `julia --bug-report=rr` tool — the `rr` dump was uploaded to https://s3.amazonaws.com/julialang-dumps/reports/2020-08-28T15-12-54-jmert.tar.zst

Julia version:
```
julia> versioninfo()
Julia Version 1.5.0-beta1.0
Commit 6443f6c95a (2020-05-28 17:42 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```
(I had to switch to my Intel laptop since `rr` doesn't run on Ryzen, and I didn't realize I still had the beta installed on the laptop. I can reproduce with v1.5.1 if need be.)

Test script:
```julia
using Printf

function switchcase(i, str)
    case = str
    if uppercase(case) == "A"
        @info "set case A"
        showcase = i -> @printf("case A number %i", i)
    elseif uppercase(case) == "B"
        @info "set case B"
        showcase = i -> @printf("case B number %i and some more parameters %i", i, 8)
    else
        @error("no case $case")
    end
    showcase(i)
end

switchcase(2, "C")
```

### PR DESCRIPTION
**Pull request by yuyichao**
Fixes a crash when one of the incoming value for a union value phi node is of type `Union{}`.
Incoming value of this type can be generated by try-catch.

Fix #37265

### CODE REVIEW

**Comment by yuyichao** [comment]
Note that this is likely caused by https://github.com/JuliaLang/julia/commit/8345b783993a61ba0e2865e11c51538ebf4d6237 and the bug is reproducible on 0.7.0.

File: test/core.jl [hunk 1]
```diff
@@ -7288,3 +7288,37 @@ function f37044(r)
...
+        end
+    end
+    e
+end
+@test_throws UndefVarError c37265(0)
+@test c37265(1) === a37265
+@test c37265(2) === b37265
+
+# This is much more reliable at triggering the issue.
+# Reproducible on 0.7.0+
```
Comment (KristofferC) [inline test/core.jl:7311]: FWIW, the code below passes tests on all julia versions I have locally, 1.0, 1.2, 1.4.2, 1.5. Is it supposed to be `if 0`?

**Comment by yuyichao** [comment]
Did you include the definition of `a37265` and `b37265` above? Those are required to trigger the issue but doesn't really affect the error in correctly compiled code.

**Comment by KristofferC** [comment]
I did not and it indeed crashes when those are defined.

**Comment by yuyichao** [comment]
Though FWIW, the one I had above also triggers the crash on all the versions I had locally (0.7.0, 1.1.1, 1.2.0, 1.3.1, 1.4.1). I might have made the same mistake during testing previously... Anyway, doesn't really hurt to keep both.....

File: src/codegen.cpp [hunk 2]
```diff
@@ -6867,7 +6873,9 @@ static std::pair<std::unique_ptr<Module>, jl_llvm_functions_t>
                         }
                         new_union.TIndex = RTindex;
                     }
-                    V = new_union.Vboxed ? new_union.Vboxed : ConstantPointerNull::get(cast<PointerType>(T_prjlvalue));
+                    if (VN)
+                        V = (new_union.Vboxed ? new_union.Vboxed :
+                             ConstantPointerNull::get(cast<PointerType>(T_prjlvalue)));
```
Comment (vtjnash) [inline src/codegen.cpp:6878]:
```suggestion
                        V = new_union.Vboxed ? new_union.Vboxed : V_rnull;
```

File: src/codegen.cpp [hunk 3]
```diff
@@ -6835,19 +6835,25 @@ static std::pair<std::unique_ptr<Module>, jl_llvm_functions_t>
...
                     if (tindex == 0) {
-                        V = boxed(ctx, val);
+                        if (VN)
+                            V = boxed(ctx, val);
                         RTindex = ConstantInt::get(T_int8, 0x80);
                     }
                     else {
-                        V = ConstantPointerNull::get(cast<PointerType>(T_prjlvalue));
+                        if (VN)
+                            V = ConstantPointerNull::get(cast<PointerType>(T_prjlvalue));
```
Comment (vtjnash) [inline src/codegen.cpp:6856]:
```suggestion
                        if (VN)
                            V = V_rnull;
```

**Review by vtjnash — APPROVED** [review]

File: src/codegen.cpp (hunk 2 above)
Comment (yuyichao) [reply src/codegen.cpp:6878]: Huh, I wonder how I originally missed this.... = = ....
