### PR TITLE
Fix precompilation error logging

### PR DESCRIPTION
**Pull request by yuyichao**
Fix for the modpath -> modspec change

This only cause an error when logging is enabled.

### CODE REVIEW

**Comment by vtjnash** [comment]
Bug introduced in #60018 (v1.14)

**Comment by Keno** [comment]
Should we have a test that exercises the logging code path?
