### PR TITLE
Fix source build of p7zip on FreeBSD

### LINKED ISSUE #33014: Julia 1.3 runs my script at least 10x slower than Julia 1.1 does on my computer
Please see the fuller [discourse post](https://discourse.julialang.org/t/julia-v1-3-runs-this-script-at-least-10x-slower-than-julia-v1-1-on-my-computer/27815?u=jdjohnston).

Summary: On my computer, Julia 1.3 (from about DEV.308 through current) runs the posted script at least 10x slower than Julia 1.1.1 and even Julia 1.3-DEV through about DEV.164.

My best guess is that, in mid-May, there was a deliberate design decision to be less aggressive in the use of garbage collection. I can see how that would be useful on systems with *much* RAM, but on my laptop (1879MiB, per lshw) it's not helpful. Probably true for others with limited RAM, including embedded systems. If my guess is correct, would it be reasonable to have a command-line option so the user can tune gc aggressiveness, somewhat like the existing `--optimize` option?

I've attached the script in question as a text file:
[peuler92.jl.txt](https://github.com/JuliaLang/julia/files/3527462/peuler92.jl.txt)

### LINKED ISSUE #33430: FreeBSD can't build 7z with USE_BINARYBUILDER=0
Introduced in #33125.
```
../../../../CPP/Windows/ErrorMsg.cpp:18:10: error: case value evaluates to -2147467263, which cannot be narrowed to type 'DWORD' (aka 'unsigned int') [-Wc++11-narrowing]
    case E_NOTIMPL             : txt = "E_NOTIMPL"; break ;
         ^
../../../../CPP/Common/MyWindows.h:83:19: note: expanded from macro 'E_NOTIMPL'
#define E_NOTIMPL ((HRESULT)0x80004001L)
                  ^
../../../../CPP/Windows/ErrorMsg.cpp:19:10: error: case value evaluates to -2147467262, which cannot be narrowed to type 'DWORD' (aka 'unsigned int') [-Wc++11-narrowing]
    case E_NOINTERFACE         : txt = "E_NOINTERFACE"; break ;
         ^
../../../../CPP/Common/MyWindows.h:84:23: note: expanded from macro 'E_NOINTERFACE'
#define E_NOINTERFACE ((HRESULT)0x80004002L)
                      ^
../../../../CPP/Windows/ErrorMsg.cpp:20:10: error: case value evaluates to -2147467260, which cannot be narrowed to type 'DWORD' (aka 'unsigned int') [-Wc++11-narrowing]
    case E_ABORT               : txt = "E_ABORT"; break ;
         ^
../../../../CPP/Common/MyWindows.h:85:17: note: expanded from macro 'E_ABORT'
#define E_ABORT ((HRESULT)0x80004004L)
                ^
../../../../CPP/Windows/ErrorMsg.cpp:21:10: error: case value evaluates to -2147467259, which cannot be narrowed to type 'DWORD' (aka 'unsigned int') [-Wc++11-narrowing]
    case E_FAIL                : txt = "E_FAIL"; break ;
         ^
../../../../CPP/Common/MyWindows.h:86:16: note: expanded from macro 'E_FAIL'
#define E_FAIL ((HRESULT)0x80004005L)
               ^
../../../../CPP/Windows/ErrorMsg.cpp:22:10: error: case value evaluates to -2147287039, which cannot be narrowed to type 'DWORD' (aka 'unsigned int') [-Wc++11-narrowing]
    case STG_E_INVALIDFUNCTION : txt = "STG_E_INVALIDFUNCTION"; break ;
         ^
../../../../CPP/Common/MyWindows.h:87:31: note: expanded from macro 'STG_E_INVALIDFUNCTION'
#define STG_E_INVALIDFUNCTION ((HRESULT)0x80030001L)
                              ^
../../../../CPP/Windows/ErrorMsg.cpp:23:10: error: case value evaluates to -2147024882, which cannot be narrowed to type 'DWORD' (aka 'unsigned int') [-Wc++11-narrowing]
    case E_OUTOFMEMORY         : txt = "E_OUTOFMEMORY"; break ;
         ^
../../../../CPP/Common/MyWindows.h:88:23: note: expanded from macro 'E_OUTOFMEMORY'
#define E_OUTOFMEMORY ((HRESULT)0x8007000EL)
                      ^
../../../../CPP/Windows/ErrorMsg.cpp:24:10: error: case value evaluates to -2147024809, which cannot be narrowed to type 'DWORD' (aka 'unsigned int') [-Wc++11-narrowing]
    case E_INVALIDARG          : txt = "E_INVALIDARG"; break ;
         ^
../../../../CPP/Common/MyWindows.h:89:22: note: expanded from macro 'E_INVALIDARG'
#define E_INVALIDARG ((HRESULT)0x80070057L)
                     ^
7 errors generated.
gmake[3]: *** [makefile.list:652: ErrorMsg.o] Error 1
gmake[2]: *** [makefile:17: 7za] Error 2
gmake[1]: *** [/usr/home/alex/Projects/julia/deps/p7zip.mk:28: scratch/p7zip-16.2.0/build-compiled] Error 2
```

### PR DESCRIPTION
**Pull request by ararslan**
Adds a patch from the FreeBSD Ports Collection to fix #33430. I've applied the patch conditional on FreeBSD but it seems like it could be fine to apply to the others.

Marking for backport to 1.3 since the change that broke this was also marked for 1.3.

### CODE REVIEW

**Comment by staticfloat** [comment]
I would rather apply it unconditionally.  Also, I love it when you assign an issue to me, and then go ahead and just fix it yourself.  :)

**Review by staticfloat — APPROVED** [review]
