### ISSUE TITLE
Build failure with LLVM 3.4 and 3.5

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#10376]
I get this in the recent RPM nightlies with LLVM 3.4 and 3.5:
```
debuginfo.cpp: In function 'int jl_get_llvmf_info(uint64_t, uint64_t*, uint64_t*, const llvm::object::ObjectFile**)':
debuginfo.cpp:814:30: error: 'struct ObjectInfo' has no member named 'slide'
         *slide = fit->second.slide;
                              ^
```
https://copr-be.cloud.fedoraproject.org/results/nalimilan/julia-nightlies/fedora-20-x86_64/julia-0.4.0-0.20150301.el7.centos/build.log

I guess this has been introduced by https://github.com/JuliaLang/julia/commit/1d0b067cf30a2dded54891ad6f468b8ab7b918e9. Likely an untested combination of `LLVM36` and `USE_MCJIT`.

CC: @vtjnash

**Comment by tkelman** [comment]
fixed by #10368? just waiting confirmation that it's correct to set it to 0 for llvm 3.4 or 3.5

**Comment by nalimilan** [comment]
Ah, I remembered seeing that PR, bug GitHub's search feature isn't that smart...

**Comment by nalimilan** [comment]
Closed by #10235.
