### ISSUE TITLE
"UndefVarError: .^ not defined" from "@code_llvm 1 .^ 2" in 1.0

### ISSUE THREAD

**Issue by tkf** [JuliaLang/julia#28554]
```julia
julia> @code_llvm 1 .^ 2
ERROR: UndefVarError: .^ not defined
Stacktrace:
 [1] top-level scope at none:0

julia> versioninfo()
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

It works in 0.7. But probably it does not make sense any more now that `.^` is not a function? Even so, it would be nicer to get "expression is not a function call" error.

**Comment by vtjnash** [comment]
works fine now
