### PR TITLE
Backports for Julia v0.6.3

### PR DESCRIPTION
**Pull request by ararslan**
Still to do:

- [x] #26839: Needs more careful application to the release branch, since the changes make use of changes that were not backported. @vtjnash
- [x] #26888: Needs to be merged to master first
- [x] #26902: Needs to be merged to master first
- [x] #26897: PR up against release-0.6
- [x] #26917: Needs to be merged to master first

Next steps:

- [x] Nanosoldier
- [x] PackageEvaluator

Omitted:

* CircleCI configuration, also omitted from 0.6.1 and 0.6.2.
* ~~Changes to allow building on FreeBSD, also omitted from 0.6.1 and 0.6.2. I tried backporting them this time but wasn't able to get things working, so unless someone has a vested interest in first-class FreeBSD support for 0.6.3, I'll leave them out of this release as well.~~ 0.6.3 will have FreeBSD support.

### CODE REVIEW

**Comment by ararslan** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":release-0.6")`

**Comment by ararslan** [comment]
Tests are looking good on Linux, but there seems to be a problem with the macOS build:
```
In file included from /Users/travis/build/JuliaLang/julia/src/APInt-C.cpp:3:
./llvm-version.h:3:10: fatal error: 'llvm/Config/llvm-config.h' file not found
#include <llvm/Config/llvm-config.h>
         ^
make[2]: /usr/local/Cellar/llvm39-julia/3.9.1_1/bin/llvm-config: Command not found
```

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/26915#issuecomment-384808540) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/5bcaec36420ee9853b5b27b1272fa3477249fa1d/0f5d7af_vs_41143e8/report.md). cc @ararslan

**Comment by ViralBShah** [comment]
Do we have anything to test whether the GPU infrastructure will keep working on 0.6.3? @nishanth @aviks @maleadt @MikeInnes

**Comment by maleadt** [comment]
CUDAdrv/LLVM/CUDAnative/CuArrays test fine on this branch right now.
I'll test again when the other patches land.

**Comment by ararslan** [comment]
@nanosoldier `runbenchmarks(ALL, vs=":release-0.6")`

**Comment by vchuravy** [comment]
Indeed, the support LLVM version is 3.9.1 and I think we shouldn't backport patches for versions that we didn't even have developmental support.

@iblis17 to have a particular reason for wanting to backport that patch? Are you using Julia 0.6 with LLVM 4.0.0?

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/26915#issuecomment-386143634) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/2cc24300fbea795e95ecc1d97e47de8c337d6389/40af229_vs_41143e8/report.md). cc @ararslan

**Comment by iblis17** [comment]
@vchuravy oh okay, I'm fine with not to backporting it. 
My situation is quite special. I have a Ryzen box. It's a buggy CPU. I built 0.6 with LLVM 4.0.1 + newer openblas. I manually applied that patch to get CuArrays work.

**Comment by iblis17** [comment]
FreeBSD CI build is here: https://freebsdci.julialang.org/#/builders/1/builds/9129

**Comment by ararslan** [comment]
Looks like the hashing tests caused a segfault on FreeBSD. I can't reproduce that locally. @iblis17, can you?

**Comment by iblis17** [comment]
I can access the core file, it points to `test/bitarray.jl`.
https://gist.github.com/iblis17/8fb77e32dcb94d58fa5463c76aa0f3c1

I'm building this brach on local...

**Comment by ararslan** [comment]
@iblis17 Any update on your end? Building this branch on FreeBSD 11.1 after `git clean -fdx` produces no segfaults for me in any of the tests. Perhaps the build cache on the CI worker needs to be cleared for this to work there?

**Comment by iblis17** [comment]
I don't get segfault locally also.
Rerun CI with `git clean -fdx`: https://freebsdci.julialang.org/#/builders/1/builds/9150

**Comment by iblis17** [comment]
FreeBSD CI passed now.
As your guess, seems the cache clutters things up.

**Comment by ararslan** [comment]
Great, thanks for confirming!

Once PackageEvaluator finishes this should be good to go (assuming all's well there).

**Comment by ararslan** [comment]
Barring strong objections or fixes from the authors, I'm going to remove the problematic commits from this branch.

**Comment by ViralBShah** [comment]
@Keno is travelling, so maybe good to wait a day for his response.

**Comment by ViralBShah** [comment]
A new IndexedTables has been tagged, and I wonder if that helps.

**Comment by Keno** [comment]
@vtjnash would be a better person for the world age issue. I just know how to use a debugger.

**Comment by ViralBShah** [comment]
If the PR is required to fix some other major issue, then we need to try and keep it. If not, then removing the commits is fine- but I don't fully understand the ramifications.

**Comment by ararslan** [comment]
The newest IndexedTables version still fails tests on this branch, as it doesn't deal with the `vcat` ambiguity introduced by #25777.

**Comment by ararslan** [comment]
I've removed #25777 and #26514. @vtjnash, please submit a PR either to release-0.6 or to this branch if you know how to backport that change in a non-breaking way.

**Comment by JeffBezanson** [comment]
In the IndexedTables case it looks to me like the PooledArrays method should just be more specific (since it names a declared subtype of `AbstractArray`). I'll look into it.

**Comment by ararslan** [comment]
I've reintroduced #25777 along with Jeff's specificity fix, but #26514 is still omitted. I'd like to get 0.6.3 out the door, so if someone is going to fix that for 0.6, can I request it be addressed sooner rather than later? :wink:

**Comment by vtjnash** [comment]
Let's just push it out now. You've done a great job tracking at this down and I would rather we get these 38 commits out, than wait for a couple more and get none of them.

**Comment by ararslan** [comment]
Worth doing another full PackageEvaluator run (takes ~2 days) or should I just spot check the packages that were problematic on the last run?

**Comment by ararslan** [comment]
Spot check looks good: Revise and IndexedTables both pass now. AppVeyor is getting EPERM on x86-64 as it was in a PR of Jeff's a while back, still not sure what the deal with that is.

**Comment by ararslan** [comment]
I triggered a Windows build on the buildbot to make sure about that EPERM thing. If all comes back clear, I'll merge this and go on my merry way.

**Comment by ararslan** [comment]
I haven't been able to get a Windows build to even finish building on the buildbots yet, let alone get to the tests. :confused:

**Comment by mbauman** [comment]
It'd be really nice to see if whatever fixed building release-0.6 on skylake CPUs (https://discourse.julialang.org/t/source-build-julia-0-6-0-pre-alpha-branch-fails-with-error-in-inference-ji/10689/5) is backportable.  I did a few cursory searches but didn't find the relevant commit.

**Comment by ararslan** [comment]
Current CI failures:
* macOS: Couldn't connect to GitHub when building docs
* Windows x64: EPERM
* FreeBSD: Cache issue

**Comment by tkoolen** [comment]
Thanks!

**Comment by mortenpi** [comment]
Documenter has had a few small updates since 0.11.1, so I think it would be good to bump it for v0.6.3 as well. It would be a bit more than just bumping the versions though (a couple of new options), but I could prepare a separate PR against `release-0.6` with the necessary updates.. unless it should go through some other process?

**Comment by ararslan** [comment]
Actually if you could make a PR against my branch, `aa/backports-0.6.3`, that would be even better.

**Comment by ararslan** [comment]
@SimonDanisch was able to reproduce the EPERM error in the distributed tests on Windows.

**Comment by ararslan** [comment]
I've removed the commit from #26897 to see whether that fixes the permissions error on Windows. That PR was the first time it was observed, even though the change looks entirely unrelated.

**Comment by ararslan** [comment]
Well, I can't explain why, but removing that commit seems to have fixed it.

**Comment by ararslan** [comment]
Looks like there's a network issue or something with the i686 Linux build on Travis; it keeps getting checksum mismatches then rebuilding everything. I'm not sure why it would only happen for i686 though, as the x86-64 build works fine...

**Comment by ararslan** [comment]
The branch cache probably got polluted with master somehow. That happened when I did 0.6.2 as well. Since Travis is trying to rebuild everything I'm just going to stop it since it will just eat into our CI time just to eventually time out. So this PR should be good to merge I think.
