### PR TITLE
Don't fool the compiler about variable initialization

### LINKED ISSUE #14595: Build error with ICC 15.0.2
`git bisect` shows me this was "introduced" at 82e91180ec4ce29c0b892afeee00f567c04822d5 by @drepper. Can anyone reproduce? It seems like `icc` is not being honest about whether it is `gcc` compatible.
```bash
    CC src/codegen.o
/home/kshyatt/julia/v0.5/src/codegen.cpp(4706): error: expression must be a modifiable lvalue
          JL_MARK_INITIALIZED(SP);
          ^
```

```bash
icc -v
icc version 15.0.2 (gcc version 4.8.2 compatibility)
```

### PR DESCRIPTION
**Pull request by yuyichao**
It can easily break if any change is made to the code and incorrectly suppress the compiler warning.

Revert #14403. Close #14595

Also fixes a simple compiler warning introduced just now in https://github.com/JuliaLang/julia/commit/fb8c6e956898cf8acb76d0d5c4301c8773845e3b

c.c. @kshyatt

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Since these are the only uses of `JL_MARK_INITIALIZED`, shouldn't it be removed as well?

**Comment by StefanKarpinski** [comment]
Oh, nevermind, that is the many definitions that are being removed.

**Comment by tkelman** [comment]
LGTM. We can add it back later if we need it for something else, but will have to include an icc definition if we do.

**Comment by kshyatt** [comment]
I'll test this with ICC on the machine that was sad tonight.

**Comment by kshyatt** [comment]
Just wanted to chime in again to confirm that this fixed my problem! Thanks, @yuyichao!
