### ISSUE TITLE
Julia 0.4.0-rc1 will not build on  OSX Version 10.8.5

### ISSUE THREAD

**Issue by sdacek** [JuliaLang/julia#13125]
Using xcode-select version 2311

I receive the following error in make when building signal-handeling.o
```
    CC src/signal-handling.o
In file included from signal-handling.c:62:
./signals-unix.c:40:72: error: use of undeclared identifier 'ucontext64_t'; did you mean 'ucontext_t'?
    bt_size = rec_backtrace_ctx(bt_data, MAX_BT_SIZE, (bt_context_t)&((ucontext64_t*)context)->uc_mcon...
                                                                       ^
./signals-unix.c:40:85: error: expected expression
    bt_size = rec_backtrace_ctx(bt_data, MAX_BT_SIZE, (bt_context_t)&((ucontext64_t*)context)->uc_mcon...
                                                                                    ^
2 errors generated.
make[1]: *** [signal-handling.o] Error 1
make: *** [julia-src-release] Error 2
```

**Comment by vtjnash** [comment]
```
diff --git a/src/signals-apple.c b/src/signals-apple.c
index ab3709b..ecf64ba 100644
--- a/src/signals-apple.c
+++ b/src/signals-apple.c
@@ -5,7 +5,7 @@
 #include <mach/mig_errors.h>
 #include <AvailabilityMacros.h>
 
-#ifdef MAC_OS_X_VERSION_10_9
+#ifdef MAC_OS_X_VERSION_10_9 && MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_X_VERSION_10_9
 #include <sys/_types/_ucontext64.h>
 #else
 #define __need_ucontext64_t
```
does this patch work? (use `git apply` <enter> <paste patch> <^D> to apply)

**Comment by sdacek** [comment]
After make clean, still throws the same error preceded by a warning

```
./signals-apple.c:8:30: warning: extra tokens at end of #ifdef directive [-Wextra-tokens]
#ifdef MAC_OS_X_VERSION_10_9 && MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_X_VERSION_10_9
```

**Comment by vtjnash** [comment]
sorry, i typed that wrong, just do `#if 0` for now (make clean isn't necessary, just make)

**Comment by sdacek** [comment]
I commented out the block and just have 

```
#define __need_ucontext64_t
#include <machine/_structs.h>
```

The same error still results.

**Comment by vtjnash** [comment]
does it work if you replace "machine" with "sys"?

**Comment by sdacek** [comment]
That did the trick. Thank you.

**Comment by vtjnash** [comment]
perfect. thank you for reporting and testing.

**Comment by tkelman** [comment]
backport pending 0.4, I assume?

**Comment by vtjnash** [comment]
yes

**Comment by tkelman** [comment]
backported in #13107
