### PR TITLE
Add casts to fix compile on Clang 3.7

### PR DESCRIPTION
**Pull request by ihnorton**
The other call-sites have this cast. (AFAICT travis is on Clang 3.5, maybe Clang 3.7 is stricter?)
Fixes:

```
/Users/inorton/git/jldev/src/debuginfo.cpp:1134:3: error: no matching function for call to 'processFDEs'
  processFDEs(Addr, Size, [](const char *Entry) {
  ^~~~~~~~~~~
/Users/inorton/git/jldev/src/debuginfo.cpp:1089:13: note: candidate function [with callback = (lambda at
      /Users/inorton/git/jldev/src/debuginfo.cpp:1134:27)] not viable: no known conversion from 'uint8_t *' (aka 'unsigned char *') to 'const char *'
      for 1st argument
static void processFDEs(const char *EHFrameAddr, size_t EHFrameSize, callback f)
            ^
/Users/inorton/git/jldev/src/debuginfo.cpp:1148:4: error: no matching function for call to 'processFDEs'
   processFDEs(Addr, Size, [](const char *Entry) {
   ^~~~~~~~~~~
/Users/inorton/git/jldev/src/debuginfo.cpp:1089:13: note: candidate function [with callback = (lambda at
      /Users/inorton/git/jldev/src/debuginfo.cpp:1148:28)] not viable: no known conversion from 'uint8_t *' (aka 'unsigned char *') to 'const char *'
      for 1st argument
static void processFDEs(const char *EHFrameAddr, size_t EHFrameSize, callback f)
            ^
2 warnings and 2 errors generated.
make[1]: *** [debuginfo.o] Error 1
```

cc @yuyichao

### CODE REVIEW

**Comment by tkelman** [comment]
SubArray failure unrelated, Travis failed to start? closing and reopening to fix the latter

**Comment by yuyichao** [comment]
LGTM, these are the the OSX defs so not really what I changed/tested.
