### PR TITLE
compatibility fix for ORC JIT in llvm 14

### PR DESCRIPTION
**Pull request by alexfanqi**
ORC JIT api has changed a bit in llvm 14. Although currently arm on Mac uses orc jit, the riscv port will need this.

Changes are introduced in https://github.com/llvm/llvm-project/commit/118e953b18ff07d00b8f822dfbf2991e41d6d791

### CODE REVIEW

**Comment by giordano** [comment]
Build of aarch64-apple-darwin, the only platform using ORC JIT, is failing https://buildkite.com/julialang/julia-master/builds/11178#4c047e50-b0fd-4c39-836f-33e9d815c074:
```
/Users/administrator/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-1.0/build/default-macmini-aarch64-1-0/julialang/julia-master/src/jitlayers.cpp:669:8: error: expected value in expression
#  elif
       ^
/Users/administrator/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-1.0/build/default-macmini-aarch64-1-0/julialang/julia-master/src/jitlayers.cpp:1039:41: error: unknown type name 'JLEHFrameRegistrar'; did you mean 'llvm::jitlink::EHFrameRegistrar'?
    auto ehRegistrar = std::make_unique<JLEHFrameRegistrar>();
                                        ^~~~~~~~~~~~~~~~~~
                                        llvm::jitlink::EHFrameRegistrar
/Users/administrator/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-1.0/build/default-macmini-aarch64-1-0/julialang/julia-master/usr/include/llvm/ExecutionEngine/JITLink/EHFrameSupport.h:25:7: note: 'llvm::jitlink::EHFrameRegistrar' declared here
class EHFrameRegistrar {
      ^
```

File: src/jitlayers.cpp [hunk 1]
```diff
@@ -644,6 +649,24 @@ class JLDebuginfoPlugin : public ObjectLinkingLayer::Plugin {
 }
 
 # ifdef LLVM_SHLIB
+#  if JL_LLVM_VERSION >= 140000
+class JLEHFrameRegistrar final : public jitlink::EHFrameRegistrar {
+public:
+    Error registerEHFrames(orc::ExecutorAddrRange EHFrameSection) override {
+        register_eh_frames(
+            reinterpret_cast<uint8_t *>(EHFrameSection.Start.getValue()),
```
Comment (pchintalapudi) [inline src/jitlayers.cpp:657]: I would recommend using `EHFrameSection.Start.toPtr<uint8_t *>()` here and in deregistering for terseness/clarity

**Comment by alexfanqi** [comment]
Sorry, my bad. It was a silly mistake.

Address comment. Use toPtr

File: src/jitlayers.cpp [hunk 2]
```diff
@@ -644,6 +649,24 @@ class JLDebuginfoPlugin : public ObjectLinkingLayer::Plugin {
 }
 
 # ifdef LLVM_SHLIB
+#  if JL_LLVM_VERSION >= 140000
+class JLEHFrameRegistrar final : public jitlink::EHFrameRegistrar {
+public:
+    Error registerEHFrames(orc::ExecutorAddrRange EHFrameSection) override {
+        register_eh_frames(
```
Comment (pchintalapudi) [inline src/jitlayers.cpp:656]: Looking at this more closely, it seems that only the arguments and unpacking of the arguments have changed between the versions, and the class structure overall is still the same. I wonder if we can simply define two macros, one for the argument and one to unpack it into (de)register_eh_frames which changes between 140000 and below. This would reduce the amount of code that's guarded by the preprocessor here.

Comment (alexfanqi) [reply src/jitlayers.cpp]: Thanks for the suggestion. Does this look more clean?

**Review by pchintalapudi — APPROVED** [review]
