### ISSUE TITLE
Address sanitizer woes

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#13858]
If I do a fresh pull and compile of Julia master with the following `Make.user`:

```
USECLANG=1
SANITIZE=1

LLVM_VER=3.7.0
USE_LLVM_SHLIB=1
LLVM_ASSERTIONS=1
```

compilation errors out with ASAN-related undefined references. I [think](https://github.com/google/sanitizers/issues/380) this happens because of the `-Wl,--no-undefined` flag some deps are compiled with. Maybe the dependencies shouldn't honour `SANITIZE`?

Anyway, if I build the deps with `SANITIZE=0`, and afterwards clean & rebuild julia with `SANITIZE=1`, the `createAddressSanitizerFunctionPass` call craps out at runtime:

```
Pass 'AddressSanitizerFunctionPass' is not initialized.
Verify if there is a pass dependency cycle.
Required Passes:
    Dominator Tree Construction
julia-debug: /tmp/julia/deps/srccache/llvm-3.7.0/lib/IR/LegacyPassManager.cpp:635: void llvm::PMTopLevelManager::schedulePass(llvm::Pass *): Assertion `PI && "Expected required passes to be initialized"' failed.
```

I'm not sure if and how we're supposed to initialize the pass.
If I comment out the pass, I get a bit further, until building `inference0.ji` segfaults during `interference.jl`. I don't knpw if ASAN support is supposed to be functional on `master`?

I'm testing julia `master` on Linux (Debian Jessie and Arch), using LLVM 3.7 (both compiling and `LLVM_VER`).

**Comment by maleadt** [comment]
Any idea on this one? Just tested on `master`, still having the issue with `createAddressSanitizerFunctionPass`, and when commented out first a stack-overflow (remedied with `ulimit -s $BIG_NUMBER`), then a segfault during `inference.jl` somewhere below `julia_type_to_di`.

@Keno, you added the ASAN pass to the codebase back in July, do you nowadays still manage to compile with `SANITIZE=1`?

**Comment by Keno** [comment]
This is an LLVM bug. I fixed it upstream (https://github.com/llvm-mirror/llvm/commit/bb5ca273e0ee58bededeab057f8b360181660b02), but you should be able to fix it manually by calling the appropriate initialization function before adding the pass to the FPM.

**Comment by maleadt** [comment]
OK thanks, the build succeeds with this change. Should I create a PR to include this in Julia?
```patch
diff --git a/src/codegen.cpp b/src/codegen.cpp
index 15a07a2..432837f 100644
--- a/src/codegen.cpp
+++ b/src/codegen.cpp
@@ -6366,6 +6366,10 @@ static void init_julia_llvm_env(Module *m)
 
 #ifdef __has_feature
 #   if __has_feature(address_sanitizer)
+#   ifndef LLVM38
+    // LLVM BUG: ASAN pass doesn't properly initialize its dependencies
+    initializeTargetLibraryInfoWrapperPassPass(*PassRegistry::getPassRegistry());
+#   endif
     FPM->add(createAddressSanitizerFunctionPass());
 #   endif
 #   if __has_feature(memory_sanitizer)
```

Part of my original problem remains though, when building the entirety of Julia with `SANITIZE=1` the deps fail due to undefined references to ASAN symbols. Seeing how there is a separate option to use ASAN with LLVM (`LLVM_SANITIZE`), maybe `SANITIZE` should not get honored when building the dependencies?

**Comment by Keno** [comment]
Which deps fail? That usually just indicates link flags that don't get propagated properly. `LLVM_SANITIZE` exists, because instrumenting LLVM significantly slows down the compile, so it can be bothersome if you're not looking for bugs in LLVM. The patch is fine, I'll merge it if you submit a PR.

**Comment by maleadt** [comment]
LLVM, actually. On a fresh checkout:

```
LSAN_OPTIONS=exitcode=0 \
make -C deps compile-llvm -j10 SANITIZE=1 USECLANG=1 LLVM_VER=3.7.0

<wait 5 min>

undefined reference to `__asan_report_store8'
...
```

I'll check whether the other fix works on LLVM 3.3 and submit a PR.

**Comment by Keno** [comment]
Ok, that configuration probably has just bitrotted in the Makefile.

**Comment by maleadt** [comment]
`pcre2` also fails: during the test suite, there's undefined ASAN symbols running the `lt-pcre2grep` binary, which makes the compilation error out.

**Comment by maleadt** [comment]
There seems to be another issue, at least on my system:

```
$ git clone

# Make the deps without SANITIZE (because of the above)
$ make USECLANG=1
$ make clean

# Make julia with SANITIZE
$ LSAN_OPTIONS=exitcode=0 make USECLANG=1 SANITIZE=1

$ ./julia
ERROR: system image file "usr/lib/julia/sys.so" not found
```

Looking through `LD_DEBUG=all`, there's ASAN again:
```
calling init: usr/lib/julia/sys.so

symbol=__asan_init_v3;  lookup in file=./julia [0]
...
usr/lib/julia/sys.so: error: symbol lookup error: undefined symbol: __asan_init_v3 (fatal)
```

**Comment by maleadt** [comment]
Found what I was missing: the ASAN runtime isn't forwards compatible, so `createAddressSanitizerFunctionPass` was adding references corresponding with the `LLVM_VER` of my  choosing whilst the runtime was provided by my system Clang. Concretely, LLVM 3.7's ASAN makes use of `__asan__init_v5`, while 3.5's ASAN provides `__asan__init`.

Document this issue, or forcibly make `SANITIZE=1` enable `BUILD_LLVM_CLANG` and use that as main compiler?

**Comment by maleadt** [comment]
Found another issue contributing to this issue: `DEPS_CFLAGS += $(SANITIZE_OPTS)` in `Make.inc` which applies the sanitizer CFLAGS to all deps, unconditionally. Many deps seem incompatible with this because of using `-Wl,--no-undefined`, and it also makes the separate `LLVM_SANITIZE` option redundant (or worse, breaks LLVM when `SANITIZE=1` and `LLVM_SANITIZE=0`).

Proposal: disable sanitizer support for all deps (ie. don't assign `SANITIZE_OPTS` to `DEPS_C(XX)FLAGS`), except for LLVM through the use of `LLVM_SANITIZE`?

**Comment by maleadt** [comment]
This has mostly been resolved, I've been happily building with `SANITIZE=1` and `LLVM_SANITIZE=1` for some time now (with the build now also passing after some fixes). Only tricky part is that the LLVM versions have to match up perfectly, so I tend to use two out-of-tree builds with one only doing `deps/install-llvm` with `LLVM_BUILD_CLANG=1` and the other using that toolchain for the rest of the build. Maybe we should document this somewhere.
