### PR TITLE
Add support for LLVM 19

### PR DESCRIPTION
**Pull request by Zentrik**
Just testing this still works with LLVM 18.

### CODE REVIEW

File: src/debuginfo.cpp [hunk 1]
```diff
@@ -287,7 +287,7 @@ void JITDebugInfoRegistry::registerJITObject(const object::ObjectFile &Object,
     uint8_t *catchjmp = NULL;
     for (const object::SymbolRef &sym_iter : Object.symbols()) {
         StringRef sName = cantFail(sym_iter.getName());
-        if (sName.equals("__UnwindData") || sName.equals("__catchjmp")) {
+        if (sName == "__UnwindData" || sName == "__catchjmp") {
```
Comment (giordano) [inline src/debuginfo.cpp:290]: In which version of llvm was this operator introduced? We currently still need to support llvm 15 on master (llvm version of latest stable series), or llvm 16 by the time Julia v1.11 will be released (hopefully soon enough)

Comment (Zentrik) [reply src/debuginfo.cpp:290]: I believe it was there 15 years ago. I can confirm when I'm next at a computer.

Comment (Zentrik) [reply src/debuginfo.cpp:290]: It was introduced with StringRef, https://github.com/llvm/llvm-project/commit/25f9fc58511807f712d7789a09157da2986f52d1, so llvm 2.

File: src/disasm.cpp [hunk 2]
```diff
@@ -1172,7 +1178,11 @@ class LineNumberPrinterHandler : public AsmPrinterHandler {
         Buffer.clear();
     }
 
+#if JL_LLVM_VERSION >= 190000
+    virtual void setSymbolSize(const MCSymbol *Sym, uint64_t Size) {}
+#else
     virtual void setSymbolSize(const MCSymbol *Sym, uint64_t Size) override {}
+#endif
     //virtual void beginModule(Module *M) override {}
```
Comment (vtjnash) [inline src/disasm.cpp:1186]: Dropping override is typically very concerning and indicates this part of the change is wrong. Notably, AsmPrinterHandler was renamed to DebugHandlerBase and addAsmPrinterHandler was renamed addDebugHandler so that a new incompatible API could use the existing names. (117b53ae38428ca66eaa886fb432e6f09db88fe4)

**Comment by vchuravy** [comment]
> Just testing this still works with LLVM 18.

That's generally my preferred strategy, opening small incremental PRs that add support for upstream changes,
before then switching over.

**Comment by maleadt** [comment]
FWIW, looks like the ITTAPI patch doesn't apply on top of the latest `julia-release/19.x`. (Why do we even carry that patch here instead of applying it on our fork?)

**Comment by Zentrik** [comment]
Looks like we do that because we wanted to avoid rebuilding LLVM. Moved to fork.

**Comment by maleadt** [comment]
```
/home/tim/Julia/src/julia/src/jitlayers.cpp: In member function 'void JuliaOJIT::enableIntelJITEventListener()':
/home/tim/Julia/src/julia/src/jitlayers.cpp:1996:9: error: 'TT' was not declared in this scope; did you mean 'TM'?
 1996 |     if (TT.isOSBinFormatELF()) {
      |         ^~
      |         TM
```

Looks like a typo introduced in https://github.com/JuliaLang/julia/pull/54841; that should be `TM->getTargetTriple().isOSBinFormatELF()`.

**Comment by maleadt** [comment]
@Zentrik Are you OK with merging this already so that I can more easily work on https://github.com/JuliaLang/julia/pull/56105? The actual PR switching to LLVM 19 (now that the JLLs are being built) will presumable take a while longer to get merged.

**Comment by Zentrik** [comment]
Go ahead
