### PR TITLE
Fix reflection macros when using splatting

### LINKED ISSUE #13264: `@which` not working with splatting
This used to work in 0.3 but not on 0.4-RC2:
```
julia> h(x...) = x; x=1:5;

julia> @which h(x...)
ERROR: ArgumentError: argument is not a generic function
 in methods at ./reflection.jl:140
 in which at ./reflection.jl:292
```

Macro-expandsion suggests that something changed in 0.4:
```
julia> macroexpand(:(@which h(x...)))
:(Base.which(top(_apply),(Base.typesof)((top(getfield))(Main,:call),h,x)))
```
vs 0.3:
```
julia> macroexpand(:(@which h(x...)))
:(Base.which(h,Base.typesof(x...)))
```

### PR DESCRIPTION
**Pull request by andreasnoack**
...by fixing the splatting branch of `gen_call_with_extracted_types`. The branch to handle splatting was added in https://github.com/JuliaLang/julia/commit/9e525744cf9de28cf248292b54f7aa07071b923b but I think it was shadowed by the branch in line 115 from the same commit because the splatting branch was broken and nobody has noticed.

This fixes #13264

### CODE REVIEW

File: base/interactiveutil.jl [hunk 1]
```diff
@@ -244,19 +244,15 @@ function gen_call_with_extracted_types(fcn, ex0)
                     Expr(:call, typesof, map(esc, args[2:end])...))
     end
     ex = expand(ex0)
-    if isa(ex, Expr) && ex.head == :call
-        return Expr(:call, fcn, esc(ex.args[1]),
-                    Expr(:call, typesof, map(esc, ex.args[2:end])...))
-    end
-    exret = Expr(:call, :error, "expression is not a function call or symbol")
     if !isa(ex, Expr)
         # do nothing -> error
```
Comment (mauro3) [inline base/interactiveutil.jl]: Remove that comment

**Comment by mauro3** [comment]
LGTM

Not really part of this PR but maybe change anyways: on line [171](https://github.com/JuliaLang/julia/pull/13277/files#diff-369ee0dda5da727577cc62809d6e5c38R271) replace `@which` with `@$(fcn)`.

Probably should be backported to 0.4 as this is a bug/regression.

**Comment by andreasnoack** [comment]
@mauro3 Thanks for the comments. I've also changed the `@which` as you suggested, but I don't know how often that branch is reached and I couldn't come up with a good `:thunk` to use as test.

**Comment by mauro3** [comment]
I don't even know what a `:thunk` is... if I ever encounter one I'll add a test case.
