### PR TITLE
Fix threading build

### LINKED ISSUE #15608: JULIA_THEADS=1 build broken by c29bff1
See #15556
Can this be made a milestone 0.5.0 issue?

```
    CC src/threading.o
/home/sachs/src/julia-multithreading/src/threading.c: In function ‘jl_threading_run’:
/home/sachs/src/julia-multithreading/src/threading.c:394:5: error: too many arguments to function ‘jl_get_specialization1’
     jl_lambda_info_t *li = jl_get_specialization1(argtypes, NULL);
     ^
In file included from /home/sachs/src/julia-multithreading/src/threading.c:23:0:
/home/sachs/src/julia-multithreading/src/julia_internal.h:266:19: note: declared here
 jl_lambda_info_t *jl_get_specialization1(jl_tupletype_t *types);
                   ^
make[1]: *** [threading.o] Error 1
make: *** [julia-src-release] Error 2
```

### PR DESCRIPTION
**Pull request by yuyichao**
- Fix signature of `jl_get_specialization1`
- Fix emission of `jltls_states_func_ptr` in sysimg.

The change in https://github.com/JuliaLang/julia/pull/15556 was folded by github.....

Fix #15608

### CODE REVIEW

**Comment by JeffBezanson** [comment]
lgtm. @vtjnash ?

**Comment by yuyichao** [comment]
I'm not really sure if this works on llvm 33

**Comment by vtjnash** [comment]
lgtm
