### ISSUE TITLE
Building v1.10.0 on Windows using MinGW fails

### ISSUE THREAD

**Issue by Titas22** [JuliaLang/julia#52646]
Hi,

I'm trying to compile **Julia v1.10** on **Windows** unsing **MinGW**. I had no issues in the past (v1.8.x/v1.9.x) but seems to not be working even after a completely fresh reinstal of MSYS and re-cloning the repo.

The error I get is this:
```
make[2]: x86_64-w64-mingw32-ar: No such file or directory
make[2]: *** [Makefile:81: libutf8proc.a] Error 127
make[1]: *** [/c/julia/deps/utf8proc.mk:13: scratch/utf8proc-1cb28a66ca79a0845e99433fd1056257456cef8b/build-compiled] Error 2
make[1]: *** Waiting for unfinished jobs....
...
...
make: *** [Makefile:75: julia-deps] Error 2
```

I believe it's related to `x86_64-w64-mingw32-ar.exe` being named differently or called wrongly in the build process? The files that do exist are `ar.exe` and `x86_64-w64-mingw32-gcc-ar.exe` after installing all the `mingw-w64-x86_64-gcc` as instructed [here](https://docs.julialang.org/en/v1/devdocs/build/windows/#Compiling-with-MinGW/MSYS2)

**Comment by Titas22** [comment]
Creating a copy of the already existing `ar.exe` and naming it `x86_64-w64-mingw32-ar.exe` allowed the process to go further until another missing file:

```
/bin/sh: line 5: x86_64-w64-mingw32-windres: command not found
make[1]: *** [Makefile:77: julia_res.o] Error 127
make[1]: *** Waiting for unfinished jobs....
    PERL base/errno_h.jl
    PERL base/features_h.jl
    PERL base/file_constants.jl
    CC usr/bin/libccalltest.dll
make: *** [Makefile:94: julia-cli-release] Error 2
make: *** Waiting for unfinished jobs....
```

Again, `windres.exe` exists instead of `x86_64-w64-mingw32-windres.exe`

**Comment by Titas22** [comment]
This was also the case for `x86_64-w64-mingw32-objcopy.exe` existing as `objcopy.exe` instead. 

After creating a copy of that the build seemed to be going for a while but ended up with the following error which I cannot understand:
```
    LINK usr/bin/libjulia-internal.dll
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./runtime_intrinsics.o: in function `jl_trunc_llvm_withtype16':
C:/julia/src/runtime_intrinsics.c:1453:(.text+0x932b): undefined reference to `truncf'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/julia/src/runtime_intrinsics.c:1453:(.text+0x9673): undefined reference to `truncf'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./flisp/libflisp.a(flisp.o): in function `strtoull_0b0o':
C:/julia/src/flisp/read.c:29:(.text+0x117cb): undefined reference to `strtoull'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./flisp/libflisp.a(flisp.o): in function `isnumtok_base':
C:/julia/src/flisp/read.c:92:(.text+0x11a60): undefined reference to `strtoll'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/julia/usr/lib/libLLVMSupport.a(APInt.cpp.obj):APInt.cpp:(.text$_ZNK4llvm5APInt4sqrtEv+0x84): undefined reference to `round'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/julia/usr/lib/libLLVMSupport.a(APInt.cpp.obj):APInt.cpp:(.text$_ZNK4llvm5APInt4sqrtEv+0x2bf): undefined reference to `round'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/julia/usr/lib/libLLVMSupport.a(APInt.cpp.obj):APInt.cpp:(.text$_ZNK4llvm5APInt4sqrtEv+0x9fc): undefined reference to `round'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../lib/libmingwex.a(lib64_libmingwex_a-mingw_vfscanf.o): in function `__mingw_sformat':
C:/M/B/src/mingw-w64/mingw-w64-crt/stdio/mingw_vfscanf.c:1081:(.text+0x1506): undefined reference to `strtoll'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/M/B/src/mingw-w64/mingw-w64-crt/stdio/mingw_vfscanf.c:1083:(.text+0x2d46): undefined reference to `strtoull'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [Makefile:376: /c/julia/usr/bin/libjulia-internal.dll] Error 1
make: *** [Makefile:91: julia-src-release] Error 2
```

**Comment by inkydragon** [comment]
I can confirm the issue with v1.10.0; master ~~work fine~~ (https://github.com/JuliaLang/julia/issues/51740).

**Comment by Titas22** [comment]
Works in v1.11 so happy to close

**Comment by Zentrik** [comment]
I hit this issue `x86_64-w64-mingw32-ar: No such file or directory`, turns out I had a `Make.user` file with `XC_HOST = x86_64-w64-mingw32`. Removing that fixed it
