### PR TITLE
Add static to inline statement, Fix #45181

### LINKED ISSUE #45181: Apple ARM64 debug build broken
```
    LINK build/dev/usr/lib/libjulia-internal-debug.1.9.dylib
Undefined symbols for architecture arm64:
  "_ptrauth_strip", referenced from:
      _jl_rec_backtrace in stackwalk.dbg.obj
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Caused by https://github.com/JuliaLang/julia/pull/45110.

### PR DESCRIPTION
**Pull request by gbaraldi**
Just inline meant the symbol did not get compiled so we got an undefined reference error.

### CODE REVIEW

**Review by maleadt — APPROVED** [review]
Rebased to give CI another change to run, but this seems to work locally.
