### PR TITLE
Make sure `reachable_var` not falls into infinite recusion.

### PR DESCRIPTION
**Pull request by N5N3**
Fix the regression caused by 36cd9c62f921abf700bb2f30d750b6a5d859a428.
This caused a precompile failure in Pkgeval (https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/36cd9c6_vs_79e29e3/AngularMomentumAlgebra.primary.log).
Test added.

### CODE REVIEW

**Review by vtjnash — COMMENTED** [review]
LGTM. I think `current_env_length` is on your other PR though?

```
/Users/administrator/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-1.0/build/default-macmini-aarch64-1-0/julialang/julia-master/src/subtype.c:2320:15: error: implicit declaration of function 'current_env_length' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    int len = current_env_length(e);
```

**Review by vtjnash — APPROVED** [review]
