### ISSUE TITLE
Build breakage on arm

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#14039]
On the current master  (commit 4e904a675cb1f4896ed1df8515fb536f233e2b2d):

````
    CC src/threadgroup.o
/home/viral/julia/src/threadgroup.c:10:23: fatal error: immintrin.h: No such file or directory
 #include <immintrin.h>
````

Perhaps this should be conditional on a certain kind of X86 architecture?

**Comment by ViralBShah** [comment]
Perhaps the entire threading should be X86 only.

This should have first happened when threadgroup.c was introduced in 5cdc03b31b94ddc60e6a806a33e0101bb3bb6ea0. Do we need to build it if threads are not being enabled by default?

**Comment by thiagopeixoto** [comment]
It's happening on ppcle64 as well.

**Comment by kpamnany** [comment]
Apologies. I now recall, faintly, that Linux does run on other architectures... ;-)

Thanks to @yuyichao for the fixes.
