### ISSUE TITLE
Building with `USE_SYSTEM_LIBUNWIND=1` is broken

### ISSUE THREAD

**Issue by topolarity** [JuliaLang/julia#57744]
```julia
/usr/bin/ld: ./threading.o: in function `jl_init_threadtls':
/home/topolarity/repos/julia2/src/threading.c:404: undefined reference to `unw_ensure_tls'
```

Seems to have been broken by https://github.com/JuliaLang/julia/commit/267d0dcae2240adc5acb11ed380d9b3037d46e3a which added a symbol that was never upstreamed

**Comment by svmhdvn** [comment]
I am running into this right now as I port Julia 1.12.0-beta2 to FreeBSD. Any updates on investigating this?
