### ISSUE TITLE
Error when try build from AUR in manjaro

### ISSUE THREAD

**Issue by subzeroDevelopment** [JuliaLang/julia#15507]
yaourt throws this line and don't finish build.

```
/tmp/yaourt-tmp-subzero/aur-julia-git/src/julia/src/codegen.cpp: In function
‘void jl_extern_c(jl_function_t*, jl_value_t*, jl_value_t*, char*)’:
/tmp/yaourt-tmp-subzero/aur-julia-git/src/julia/src/codegen.cpp:1304:65: error: invalid conversion from ‘void*’ to ‘uint64_t {aka long unsigned int}’ [-fpermissive]
                     (void*)getAddressForOrCompileFunction(llvmf));
```

[pao: quoting]

**Comment by pao** [comment]
You'll probably need to bring this up with the Arch package maintainer to determine whether there is an upstream bug.

**Comment by pao** [comment]
The code in question was introduced in https://github.com/JuliaLang/julia/commit/5adc522ffa320c72f0cf6f97b756a667a5dfbb15

**Comment by yuyichao** [comment]
The upstream is fine and this is due to https://github.com/JuliaLang/julia/pull/15472#discussion_r55929882

**Comment by yuyichao** [comment]
And I believe this is MCJIT specific.

**Comment by pao** [comment]
Sorry, I meant "upstream" as in "Julia, relative to AUR", not "LLVM". So this is valid and should be retitled, it sounds like?

**Comment by yuyichao** [comment]
FWIW I believe this is also likely 32bit only....

**Comment by barche** [comment]
I have the same error building on Arch, the updated fix in PR #15472 should build on all platforms. If you want a quick fix on arch, remove the `(*void)`.

**Comment by yuyichao** [comment]
OT: I've been putting pre-compiled version of julia dependencies into the [ArchLinux CN repo](https://github.com/archlinuxcn/repo) which should include everything that is not in the official repo (or the official repo is not new enough). This includes libunwind-git, openspecfun-git, openblas-lapack-git, libutf8proc-git, openlibm-git and llvm-julia (including a hack to enable ORCJIT in julia, not in the repo yet but should be ready soon).

**Comment by pao** [comment]
So is this fixed by https://github.com/JuliaLang/julia/commit/f7ab0e22e694f22c6dd73c1e6540592068062f9f?

**Comment by yuyichao** [comment]
Should be.
