### ISSUE TITLE
CompilerSupportLibraries' libmsvcrt.a  and msys2+mingw64  build failed

### ISSUE THREAD

**Issue by armgong** [JuliaLang/julia#48081]
today use msys2+mingw64 (both pacman -Syu to newest version) build julia on windows,use default Make.inc, nothing changed. when link libjulia-internal.dll , it failed and report following error.  after replace libmsvcrt.a in CompilerSupportLibraries  with mingw64's, build and run ok.
**Could someone check libmsvcrt.a in CompilerSupportLibraries?**
~~~bash
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./flisp/libflisp.a(flisp.o): in function `strtoull_0b0o':
D:\src\julia\src\flisp/read.c:29: undefined reference to `strtoull'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./flisp/libflisp.a(flisp.o): in function `isnumtok_base':
D:\src\julia\src\flisp/read.c:92: undefined reference to `strtoll'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../lib/libmingwex.a(lib64_libmingwex_a-mingw_vfscanf.o): in function `__mingw_sformat':
C:/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/stdio/mingw_vfscanf.c:1081: undefined reference to `strtoll'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/stdio/mingw_vfscanf.c:1083: undefined reference to `strtoull'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [Makefile:365: /d/src/julia/usr/bin/libjulia-internal.dll] Error 1
make: *** [Makefile:91: julia-src-release] Error 2
~~~

**Comment by giordano** [comment]
>  Could someone check libmsvcrt.a in CompilerSupportLibraries?

What do you want to check specifically?

**Comment by armgong** [comment]
Already checked,the strtoll and strtoll not defined in CSL libmsvcrt.a.
Maybe we need replace libmsvcrt in CSL with mingw64 newest?

**Comment by vtjnash** [comment]
It is a version mismatch. I thought we had an issue about this already? The regression was introduced by https://github.com/JuliaLang/julia/pull/47332 as discussed in https://github.com/JuliaLang/julia/pull/45582#issuecomment-1309110462

**Comment by armgong** [comment]
sorry，missing them.
Btw , build ok with cygwin with CSL ,but have issue with msys2+mingw64

**Comment by inkydragon** [comment]
Maybe we don't `libmsvcrt.a`.

This patch works for me on julia master (8e19fbbfdb)
test with:
- MSYS2 `x86_64-w64-mingw32/12.2.0`
- Cygwin + gcc 11.3.0
```patch
diff --git a/Makefile b/Makefile
index c080f0d144..a33fd6d873 100644
--- a/Makefile
+++ b/Makefile
@@ -276,7 +276,6 @@ endif
        # These are files from mingw32 and required for creating shared libraries like our caches.    
        -$(INSTALL_M) $(build_libdir)/libgcc_s.a $(DESTDIR)$(libdir)/
        -$(INSTALL_M) $(build_libdir)/libgcc.a $(DESTDIR)$(libdir)/
-       -$(INSTALL_M) $(build_libdir)/libmsvcrt.a $(DESTDIR)$(libdir)/
 else
 
 # Copy over .dSYM directories directly for Darwin
diff --git a/base/linking.jl b/base/linking.jl
index fb9f6d087a..c430b14963 100644
--- a/base/linking.jl
+++ b/base/linking.jl
@@ -133,7 +133,7 @@ function link_image_cmd(path, out)
     SHLIBDIR = "-L$(shlibdir())"
     LIBS = is_debug() ? ("-ljulia-debug", "-ljulia-internal-debug") : ("-ljulia", "-ljulia-internal")
     @static if Sys.iswindows()
-        LIBS = (LIBS..., "-lopenlibm", "-lssp", "-lgcc_s", "-lgcc", "-lmsvcrt")
+        LIBS = (LIBS..., "-lopenlibm", "-lssp", "-lgcc_s", "-lgcc")
     end
 
     V = VERBOSE[] ? "--verbose" : ""
diff --git a/deps/csl.mk b/deps/csl.mk
index 457e276c66..9da67bd4d9 100644
--- a/deps/csl.mk
+++ b/deps/csl.mk
@@ -104,4 +104,10 @@ distclean-csl: clean-csl
 
 else
 $(eval $(call bb-install,csl,CSL,true))
+
+# we don't need libmsvcrt.a
+ifeq ($(OS),WINNT)
+$(shell rm -f $(build_libdir)/libmsvcrt.a)
+endif
+
 endif
```

**Comment by stahta01** [comment]
Work around tested under MSys2 MINGW64 Binary Build with release-1.9 git branch
```
make -C deps install-csl && \
cp ${MINGW_PREFIX}/lib/libmsvcrt.a ./usr/lib/libmsvcrt.a && \
make
```

**Comment by stahta01** [comment]
I am now having this problem under Cygwin; I am guessing that the mingw64-x86_64-runtime was updated to 11.0.1-1.

Tim S.

**Comment by inkydragon** [comment]
> How come CI doesn't run into this? Are we using cygwin, or cross-compiling?

Windows CI using MSYS2 wrapped in docker, which uses an older version of GCC (12.2.0), so this problem does not occur.

https://github.com/JuliaCI/rootfs-images/blob/main/windows/package-x86_64/Dockerfile

The GCC in MSYS2 is rolling updated, so this problem may occur repeatedly.

----

I also have some questions
- Why do we need CompilerSupportLibraries.jl
- Is there any harm if we always package the latest crt?

It might be possible to do some checking of the crt version at compile time and automatically use the newer libraries.

**Comment by c42f** [comment]
I just ran into this too.  If you're testing the i686 build on cygwin, it looks like you need this libmsvcrt:

```
cp /usr/i686-w64-mingw32/sys-root/mingw/lib/libmsvcrt.a ./usr/lib/libmsvcrt.a
```

**Comment by fatteneder** [comment]
I also ran into this. Leaving some instructions here, mostly for my future self in case I loose the pin for the VM again :laughing:.

I am running windows in a VM and used `MSYS2` with
```sh
uname -a
MINGW64_NT-10.0-22621 test-julia 3.4.7.x86_64 2023-07-14 16:57 UTC x86_64 Msys

gcc --version
gcc.exe (Rev1, Built by MSYS2 project) 13.2.0
...
```

I ended up copying `/mingw64/lib/libmsvcrt.a` to `<git-root>/usr/lib/libmsvcrt.a`.

I also ran into an issue where the symlink of `base/JuliaSyntax` was pointing nowhere. Fixing that with `ln -s` was also troublesome, because it complained of directories not existing etc. but the same commands worked on my Linux box. The trick was to create a link in the same directory as the source and then rename and move it to `base/JuliaSyntax`.
In general, `ln` seems to be broken because after the build finished there was no `julia` link inside the git root dir ...
