### ISSUE TITLE
JULIA_THEADS=1 build broken by c29bff1

### ISSUE THREAD

**Issue by josefsachsconning** [JuliaLang/julia#15608]
See #15556
Can this be made a milestone 0.5.0 issue?

```
    CC src/threading.o
/home/sachs/src/julia-multithreading/src/threading.c: In function ‘jl_threading_run’:
/home/sachs/src/julia-multithreading/src/threading.c:394:5: error: too many arguments to function ‘jl_get_specialization1’
     jl_lambda_info_t *li = jl_get_specialization1(argtypes, NULL);
     ^
In file included from /home/sachs/src/julia-multithreading/src/threading.c:23:0:
/home/sachs/src/julia-multithreading/src/julia_internal.h:266:19: note: declared here
 jl_lambda_info_t *jl_get_specialization1(jl_tupletype_t *types);
                   ^
make[1]: *** [threading.o] Error 1
make: *** [julia-src-release] Error 2
```
