### ISSUE TITLE
`Int(true) == 255` with broadcasting?

### ISSUE THREAD

**Issue by MarcMush** [JuliaLang/julia#52127]
only in 1.9.0-1.9.3, I get this strange bug (not 1.8, not 1.10.0-rc1)

```julia
julia> f(n)=(n-=1)<0||[f(n)]
f (generic function with 1 method)

julia> Int.(f.(0))
255

julia> a = f.(0)
true

julia> Int.(a)
1

julia> Int.(true)
1
```

It seems to happen only when `f` is non type-stable

**Comment by BioTurboNick** [comment]
I reproduced your issue. If I provide a type annotation to `f` it works:
```
julia> f(n) = (n-=1) < 0 || [f(n)]
f (generic function with 1 method)

julia> Int.(f.(0))
255

julia> f(n)::Bool = (n-=1) < 0 || [f(n)]
f (generic function with 1 method)

julia> Int.(f.(0))
1
```

**Comment by BioTurboNick** [comment]
Curious...

```
julia> bitstring(f.(0))
"00000001"

julia> bitstring.(f.(0))
"00001111"
```

**Comment by giordano** [comment]
I haven't run `git bisect`, but

* works on 6dae654e91 (commit before upgrade to LLVM 14)
* doesn't work on a12c2f0a0dcf39fd8c8a0130b1df4a0a059828ca (commit of upgrade to LLVM 14)
* doesn't work on b2273d3954 (commit before upgrade to LLVM 15)
* I couldn't build 190f84180883eb498cb7b7ed27e10af9a6c62863 (commit of upgrade to LLVM 15) because I'm getting compilation errors

Everything points to a bug in LLVM 14.

**Comment by vtjnash** [comment]
Looks like our generated IR here is wrong. It is not legal to take this bitcast, since most of the bits are undef:
```
julia> @code_llvm optimize=false f(0)

L4:                                               ; preds = %top
  store i1 %8, i1* %2, align 1
  %12 = bitcast i1* %2 to i8*
  %13 = bitcast [1 x i8]* %0 to i8*
  switch i8 1, label %union_move_skip [
    i8 1, label %union_move
  ]
```
On some versions of LLVM, it takes the liberty to replace those undef bits with -1. On other versions, it takes those liberties to instead give up and not optimize the function instead.

(can't repro this on master exactly, but can confirm the generated IR is still wrong)

**Comment by MarcMush** [comment]
indeed it seems to be LLVM 14
`first bad commit: [a12c2f0a0dcf39fd8c8a0130b1df4a0a059828ca] Upgrade to LLVM 14.0.2`
