### ISSUE TITLE
Failing to build Julia in BSD 11.3 (FreeNAS)

### ISSUE THREAD

**Issue by jakewilliami** [JuliaLang/julia#37781]
I am running
```bash
[root@computation /tmp]# ls
.font-unix  .ICE-unix   .X11-unix   .XIM-unix
[root@computation /tmp]# clear
[root@computation /tmp]# git clone https://github.com/JuliaLang/julia --branch v1.5.1
Cloning into 'julia'...
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 335347 (delta 4), reused 4 (delta 1), pack-reused 335323
Receiving objects: 100% (335347/335347), 188.06 MiB | 8.69 MiB/s, done.
Resolving deltas: 100% (250647/250647), done.
Note: switching to '697e782ab86bfcdd7fd15550241fe162c51d9f98'.
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:
  git switch -c <new-branch-name>
Or undo this operation with:
  git switch -
Turn off this advice by setting config variable advice.detachedHead to false
[root@computation /tmp]# cd
.font-unix/ .ICE-unix/  .X11-unix/  .XIM-unix/  julia/
[root@computation /tmp]# cd julia/
[root@computation /tmp/julia]# gmake
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   497  100   497    0     0    289      0  0:00:01  0:00:01 --:--:--   289
100  389k  100  389k    0     0    97k      0  0:00:03  0:00:03 --:--:--  220k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   497  100   497    0     0    488      0  0:00:01  0:00:01 --:--:--   488
100 18378  100 18378    0     0   8372      0  0:00:02  0:00:02 --:--:-- 57183
/tmp/julia/contrib/install.sh 755 /usr/local/lib/gcc9/libgfortran.so* /tmp/julia/usr/lib
/tmp/julia/contrib/install.sh 755 /usr/local/lib/gcc9/libgcc_s.so* /tmp/julia/usr/lib
/tmp/julia/contrib/install.sh 755 /usr/local/lib/gcc9/libquadmath.so* /tmp/julia/usr/lib
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   521  100   521    0     0    496      0  0:00:01  0:00:01 --:--:--   496
100 1462k  100 1462k    0     0   317k      0  0:00:04  0:00:04 --:--:--  475k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   537  100   537    0     0    490      0  0:00:01  0:00:01 --:--:--   490
100  546k  100  546k    0     0   145k      0  0:00:03  0:00:03 --:--:--  281k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   517  100   517    0     0    513      0  0:00:01  0:00:01 --:--:--   513
100  424k  100  424k    0     0   128k      0  0:00:03  0:00:03 --:--:--  322k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   455  100   455    0     0    506      0 --:--:-- --:--:-- --:--:--   505
100  187k  100  187k    0     0  72155      0  0:00:02  0:00:02 --:--:--  176k
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /tmp/julia/deps/srccache/patchelf-0.9/build-aux/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... nawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for gcc... clang -m64
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang -m64 accepts -g... yes
checking for clang -m64 option to accept ISO C89... none needed
checking whether clang -m64 understands -c and -o together... yes
checking dependency style of clang -m64... gcc3
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ -m64 accepts -g... yes
checking dependency style of clang++ -m64... gcc3
getconf is /usr/bin/getconf
-p: not found
Setting page size to 4096
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating tests/Makefile
config.status: creating patchelf.spec
config.status: executing depfiles commands
Making all in src
Making all in tests
Making install in src
 /tmp/julia/deps/srccache/patchelf-0.9/build-aux/install-sh -c -d '/tmp/julia/usr-staging/patchelf-0.9/tmp/julia/usr/tools'
  /usr/bin/install -c patchelf '/tmp/julia/usr-staging/patchelf-0.9/tmp/julia/usr/tools'
Making install in tests
 /tmp/julia/deps/srccache/patchelf-0.9/build-aux/install-sh -c -d '/tmp/julia/usr-staging/patchelf-0.9/tmp/julia/usr/share/doc/patchelf'
 /usr/bin/install -c -m 644 /tmp/julia/deps/srccache/patchelf-0.9/README '/tmp/julia/usr-staging/patchelf-0.9/tmp/julia/usr/share/doc/patchelf'
 /tmp/julia/deps/srccache/patchelf-0.9/build-aux/install-sh -c -d '/tmp/julia/usr-staging/patchelf-0.9/tmp/julia/usr/share/man/man1'
 /usr/bin/install -c -m 644 /tmp/julia/deps/srccache/patchelf-0.9/patchelf.1 '/tmp/julia/usr-staging/patchelf-0.9/tmp/julia/usr/share/man/man1'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   515  100   515    0     0    515      0  0:00:01 --:--:--  0:00:01   515
100  261k  100  261k    0     0  87632      0  0:00:03  0:00:03 --:--:--  148k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   509  100   509    0     0    506      0  0:00:01  0:00:01 --:--:--   506
100  9474  100  9474    0     0   4828      0  0:00:01  0:00:01 --:--:-- 12699
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   529  100   529    0     0    483      0  0:00:01  0:00:01 --:--:--   482
100  120M  100  120M    0     0  4175k      0  0:00:29  0:00:29 --:--:-- 8150k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   513  100   513    0     0    480      0  0:00:01  0:00:01 --:--:--   480
100 1249k  100 1249k    0     0   126k      0  0:00:09  0:00:09 --:--:--  221k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   541  100   541    0     0    497      0  0:00:01  0:00:01 --:--:--   497
100 9972k  100 9972k    0     0  1028k      0  0:00:09  0:00:09 --:--:-- 1831k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   505  100   505    0     0    489      0  0:00:01  0:00:01 --:--:--   489
100  559k  100  559k    0     0  76003      0  0:00:07  0:00:07 --:--:--  113k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   515  100   515    0     0    498      0  0:00:01  0:00:01 --:--:--   498
100 1057k  100 1057k    0     0    99k      0  0:00:10  0:00:10 --:--:--  166k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   513  100   513    0     0    482      0  0:00:01  0:00:01 --:--:--   482
100  221k  100  221k    0     0  48271      0  0:00:04  0:00:04 --:--:-- 63796
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   515  100   515    0     0    518      0 --:--:-- --:--:-- --:--:--   518
100  645k  100  645k    0     0  83897      0  0:00:07  0:00:07 --:--:--  120k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   515  100   515    0     0    469      0  0:00:01  0:00:01 --:--:--   469
100  732k  100  732k    0     0  87359      0  0:00:08  0:00:08 --:--:--  135k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   459  100   459    0     0    397      0  0:00:01  0:00:01 --:--:--   397
100  216k  100  216k    0     0  42948      0  0:00:05  0:00:05 --:--:-- 67000
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   507  100   507    0     0    470      0  0:00:01  0:00:01 --:--:--   470
100  718k  100  718k    0     0  86529      0  0:00:08  0:00:08 --:--:--  126k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   497  100   497    0     0    464      0  0:00:01  0:00:01 --:--:--   464
100  151k  100  151k    0     0  40072      0  0:00:03  0:00:03 --:--:-- 84476
ar: warning: creating libutf8proc.a
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   509  100   509    0     0    411      0  0:00:01  0:00:01 --:--:--   411
100  150k  100  150k    0     0  37461      0  0:00:04  0:00:04 --:--:-- 70897
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   511  100   511    0     0    500      0  0:00:01  0:00:01 --:--:--   500
100  618k  100  618k    0     0  78777      0  0:00:08  0:00:08 --:--:--  115k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   497  100   497    0     0    518      0 --:--:-- --:--:-- --:--:--   517
100  4183  100  4183    0     0   2217      0  0:00:01  0:00:01 --:--:-- 17213
Creating usr/etc/julia/startup.jl
Copying in usr/share/man/man1/julia.1
/tmp/julia/contrib/install.sh 755 /tmp/julia/contrib/julia-config.jl /tmp/julia/usr/share/julia/
    PERL base/pcre_h.jl
    PERL base/errno_h.jl
    PERL base/build_h.jl.phony
    PERL base/file_constants.jl
    PERL base/uv_constants.jl
    PERL base/version_git.jl.phony
    CC src/support/hashing.o
    CC src/support/timefuncs.o
    CC src/support/ptrhash.o
    CC src/support/operators.o
    CC src/support/utf8.o
    CC src/support/ios.o
    CC src/support/htable.o
    CC src/support/bitvector.o
    CC src/support/int2str.o
    CC src/support/libsupportinit.o
    CC src/support/arraylist.o
    CC src/support/strtod.o
    LINK src/support/libsupport.a
    CC src/flisp/flisp.o
    CC src/flisp/builtins.o
    CC src/flisp/string.o
    CC src/flisp/equalhash.o
    CC src/flisp/table.o
    CC src/flisp/iostream.o
    CC src/flisp/julia_extensions.o
    LINK src/flisp/libflisp.a
    CC src/flisp/flmain.o
    LINK src/flisp/flisp
    FLISP src/julia_flisp.boot
    FLISP src/julia_flisp.boot.inc
    CC src/jloptions.o
    CC src/runtime_ccall.o
    CC src/rtutils.o
    CC src/codegen.o
    CC src/llvm-ptls.o
    CC src/jltypes.o
    CC src/gf.o
    CC src/typemap.o
    CC src/smallintset.o
    CC src/ast.o
    CC src/builtins.o
    CC src/module.o
    CC src/interpreter.o
    CC src/symbol.o
    CC src/dlload.o
    CC src/sys.o
    CC src/init.o
    CC src/task.o
    CC src/array.o
    CC src/dump.o
    CC src/staticdata.o
    CC src/toplevel.o
    CC src/jl_uv.o
    CC src/datatype.o
    CC src/simplevector.o
    CC src/runtime_intrinsics.o
    CC src/precompile.o
    CC src/threading.o
    CC src/partr.o
    CC src/stackwalk.o
    CC src/gc.o
    CC src/gc-debug.o
    CC src/gc-pages.o
    CC src/gc-stacks.o
    CC src/method.o
    CC src/jlapi.o
    CC src/signal-handling.o
In file included from /tmp/julia/src/signal-handling.c:117:
./signals-unix.c:304:18: warning: incompatible integer to pointer conversion passing 'unsigned long' to parameter of type
      '__pthread_t' (aka 'struct pthread *') [-Wint-conversion]
    pthread_kill(ptls2->system_id, SIGUSR2);
                 ^~~~~~~~~~~~~~~~
/usr/include/signal.h:77:29: note: passing argument to parameter here
int     pthread_kill(__pthread_t, int);
                                ^
In file included from /tmp/julia/src/signal-handling.c:117:
./signals-unix.c:331:18: warning: incompatible integer to pointer conversion passing 'unsigned long' to parameter of type
      '__pthread_t' (aka 'struct pthread *') [-Wint-conversion]
    pthread_kill(ptls2->system_id, SIGUSR2);
                 ^~~~~~~~~~~~~~~~
/usr/include/signal.h:77:29: note: passing argument to parameter here
int     pthread_kill(__pthread_t, int);
                                ^
In file included from /tmp/julia/src/signal-handling.c:117:
./signals-unix.c:358:18: warning: incompatible integer to pointer conversion passing 'unsigned long' to parameter of type
      '__pthread_t' (aka 'struct pthread *') [-Wint-conversion]
    pthread_kill(ptls2->system_id, SIGUSR2);
                 ^~~~~~~~~~~~~~~~
/usr/include/signal.h:77:29: note: passing argument to parameter here
int     pthread_kill(__pthread_t, int);
                                ^
3 warnings generated.
    CC src/safepoint.o
    CC src/timing.o
    CC src/subtype.o
/tmp/julia/src/subtype.c:2753:84: warning: incompatible pointer types passing 'jl_datatype_t *' (aka 'struct _jl_datatype_t *') to
      parameter of type 'jl_value_t *' (aka 'struct _jl_value_t *') [-Wincompatible-pointer-types]
    if (jl_nparams(xd) == 0 || jl_nparams(xd->super) == 0 || !jl_has_free_typevars(xd))
                                                                                   ^~
./julia.h:1197:51: note: passing argument to parameter 'v' here
JL_DLLEXPORT int jl_has_free_typevars(jl_value_t *v) JL_NOTSAFEPOINT;
                                                  ^
1 warning generated.
    CC src/crc32c.o
    CC src/APInt-C.o
    CC src/processor.o
    CC src/jitlayers.o
    CC src/aotcompile.o
    CC src/debuginfo.o
    CC src/disasm.o
    CC src/llvm-simdloop.o
    CC src/llvm-muladd.o
    CC src/llvm-final-gc-lowering.o
    CC src/llvm-pass-helpers.o
    CC src/llvm-late-gc-lowering.o
    CC src/llvm-lower-handlers.o
    CC src/llvm-gc-invariant-verifier.o
    CC src/llvm-propagate-addrspaces.o
    CC src/llvm-multiversioning.o
    CC src/llvm-alloc-opt.o
    CC src/cgmemmgr.o
    CC src/llvm-api.o
    CC src/llvm-remove-addrspaces.o
    CC src/llvm-remove-ni.o
    LINK usr/lib/libjulia.so.1.5
    CC ui/repl.o
    LINK usr/bin/julia
/tmp/julia/usr/lib/libjulia.so: undefined reference to `llvm::cfg::Update<llvm::BasicBlock*>::dump() const'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[1]: *** [Makefile:86: /tmp/julia/usr/bin/julia] Error 1
gmake: *** [Makefile:78: julia-ui-release] Error 2
```

I am unsure if this is a problem with my system (running `FreeNAS-11.3-U4.1`).  I have also followed the instructions [here](https://github.com/JuliaLang/julia/blob/master/doc/build/freebsd.md).

**Comment by vtjnash** [comment]
This indicates the `-DNDEBUG` command line flag is set incorrectly during your CXX build. I am unsure however how that could have happened. Can you run `gmake VERBOSE=1` on v1.6 now?

**Comment by jakewilliami** [comment]
@vtjnash Yay, I think it works in 1.6!  I ran this:
```bash
$ git clone https://github.com/JuliaLang/julia --branch v1.6.0-rc1 && cd julia && gmake VERBOSE=1 2>&1 | tee julia-build.log
```
And [here is the output](https://pastebin.com/btp4PPnL).  Thanks!

Should this be closed now, or kept open because the original issue pertained to 1.5?
