### ISSUE TITLE
libgit2.0.23.0.dylib Build Failing on Mac OS X

### ISSUE THREAD

**Issue by odysseus9672** [JuliaLang/julia#12026]
I'm attempting to build the julia master branch on Mac OS X 10.10.4 with XCode version 6.4 Build version 6E35b. 

The top line from 'git log --oneline' is: 4bb10cd Merge pull request #12017 from JuliaLang/tk/bumppcre

The build fails with this error:

Linking C shared library libgit2.dylib
Undefined symbols for architecture x86_64:
  "_libiconv", referenced from:
      _git_path_iconv in path.c.o
  "_libiconv_close", referenced from:
      _git_path_direach in path.c.o
      _git_path_iconv_clear in path.c.o
      _git_path_diriter_free in path.c.o
      _git_path_dirload in path.c.o
  "_libiconv_open", referenced from:
      _git_path_direach in path.c.o
      _git_path_iconv_init_precompose in path.c.o
      _git_path_diriter_init in path.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/git2.dir/build.make:3286: recipe for target 'libgit2.0.23.0.dylib' failed
make[4]: *** [libgit2.0.23.0.dylib] Error 1

**Comment by tkelman** [comment]
This looks the same as #8937. Do you have some old copies of fink or macports lying around? Can you post the full output of running `make -C deps distclean-libgit2 && make -C deps install-libgit2 VERBOSE=1` to gist.github.com, and post a link to the gist here?

**Comment by odysseus9672** [comment]
I have an install of fink on this machine, and it supplies the cmake that I use. The installed version of cmake is 3.2.1. I don't have libgit2 installed via fink, though the version that is closest to what julia is trying to build compiles and installs fine.

Here's the full output from running the commands you requested:
https://gist.github.com/anonymous/4338f1a8c3ebf8dbf470

**Comment by odysseus9672** [comment]
I should add that I recently completely recompiled the fink build when I updated to 10.10.4, so there shouldn't be any orphaned or extraneous packages installed. I can supply you with the packages I have installed, if you'd like.

**Comment by tkelman** [comment]
Thanks for the info. Last time (in #8937) the problem seemed to be due to an old non-updated copy of openssl from fink, but the latest version of libgit2 looks like it isn't using openssl on osx any more. At this point I'm not sure what to do - maybe check if the copy of libiconv in `/usr/lib` has the symbols that libgit2 is trying to use? Otherwise I'd open this upstream on libgit2's issue tracker including a link to the same gist, just highlight the full `cmake` line that we're using. Maybe we could fix this by modifying our configuration options, but the libgit2 devs would know that better than me.

**Comment by odysseus9672** [comment]
Issue submitted upstream. https://github.com/libgit2/libgit2/issues/3296

**Comment by odysseus9672** [comment]
I can now rule out my Fink install as a cause of the problem. I installed the current cmake into /usr/local, and set my PATH as:
echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin

Here's a new gist that shows basically the same error crops up: https://gist.github.com/odysseus9672/24083f472ac83192b269

And a gist showing the new CMakeLists.txt: https://gist.github.com/odysseus9672/ffc9648f731e3e5c0a46

**Comment by odysseus9672** [comment]
Successful workaround found, as noted upstream. From my perspective, feel free to mark the issue closed.

**Comment by tkelman** [comment]
Thanks for the followup. For future reference, what was the iconv headers package name in fink that you had to uninstall?

**Comment by odysseus9672** [comment]
libiconv-dev is the package with the libiconv headers.

**Comment by tkelman** [comment]
I suppose we could add a troubleshooting note about this to the readme https://github.com/JuliaLang/julia/blob/master/README.md#os-x

**Comment by odysseus9672** [comment]
Generalizing the note shouldn't be too hard. Mention trying to uninstall external packages, especially ones that only need to be installed while the packages they depend on are built.

**Comment by tkelman** [comment]
I don't have a mac, so I'll leave the wording there to you if you'd like to propose a change as a PR. Otherwise we can just close this.

**Comment by odysseus9672** [comment]
"compilers in brew and MacPorts work for building Julia." I can confirm that it builds with Fink, so I'd make this: "compilers in Brew, Fink, and MacPorts work for building Julia." (going with alphabetical ordering)

What I would suggest for the build conflicts part: When building Julia, or its dependencies, libraries installed by third party package managers can redirect the compiler to use an incompatible version of the software it is looking for. One example of this happening is when a piece of software called the "linker" gives an error involving "Undefined symbols." If that happens, you can usually figure out what software package is causing the error from the names in the error text. This sort of error can be bypassed by, temporarily, uninstalling the offending package. If the offending package cannot be uninstalled by itself, it may be possible to just uninstall the development headers (for example: a package ending in "-dev" in Fink).

**Comment by tkelman** [comment]
That sounds useful. You can suggest the edit by clicking the little pencil icon in the github interface and it'll open a pull request automatically. You can add "Closes #12026" somewhere in the commit message or pull request description and it'll auto-close this issue when merged.
