### ISSUE TITLE
Build fails in fresh installation of version 1.5.0

### ISSUE THREAD

**Issue by adrianor** [JuliaLang/julia#38930]
I have been trying to compile `julia` for versions `1.5.x` I have found errors in a consistent manner. Currently I am working with version `1.5.0`. The tail of the compiling process yields 

```
/home/username/julia-last/julia/usr/include/llvm/Support/MathExtras.h:189:16: error: ‘static_assert’ was not declared in this scope
Makefile:165: recipe for target 'runtime_ccall.o' failed
make[1]: *** [runtime_ccall.o] Error 1
Makefile:75: recipe for target 'julia-src-release' failed
make: *** [julia-src-release] Error 2
```

This is very cryptic, any idea how to fix this?

My OS is

```
NAME="Linux Mint"
VERSION="18 (Sarah)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18"
VERSION_ID="18"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
UBUNTU_CODENAME=xenial
```

The compiler version is 

```
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by mgkuhn** [comment]
What OS and compiler? Does this also happen with 1.5.3?

**Comment by adrianor** [comment]
Hi, I have added the data. The issue is still for 1.5.3.

**Comment by fingolfin** [comment]
@adrianor what compiler and which version (via `cc --version` or `gcc --version`)

**Comment by fingolfin** [comment]
Mint 18 is from 2016; the error indicates missing support for `static_assert`, which was added in C11 (the C standard update from 2011). A guess would be that your compiler is "too old", and does not support C11. Or perhaps it supports it, but Julia's build system fails to enable it for some reason.

**Comment by adrianor** [comment]
Ah, that was the simple issue and the compilation was fixed. Is there any chance to add an update where it explicitly says to upgrade compilers versions? It is not really intuitive because version 1.0 does not complain, while this does.

**Comment by mgkuhn** [comment]
@adrianor You still haven't answered what compiler and which version failed (you only gave the version of `make`). Run `gcc --version` or `clang --version` and then compare that version number against the  [documented requirements for 1.5](https://github.com/JuliaLang/julia/blob/release-1.5/doc/build/build.md#required-build-tools-and-external-libraries) and [master](https://github.com/JuliaLang/julia/blob/master/doc/build/build.md#required-build-tools-and-external-libraries).

**Comment by adrianor** [comment]
So the version that failed was 

```
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
```

And I installed 
```
gcc-6 (Ubuntu 6.5.0-2ubuntu1~16.04) 6.5.0 20181026
```

The version that julia asks is `gcc & g++ (>= 4.7) `, so in principle my first gcc should have made the job, as fingolfin mentioned.

**Comment by mgkuhn** [comment]
I just tried to compile the head of git branch `release-1.5` on Ubuntu 16.04. I couldn't reproduce that particular error message (same g++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609). I get instead
```
    LINK usr/bin/julia
[...]/julia/usr/lib/libLLVM-9jl.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
[...]/julia/usr/lib/libLLVM-9jl.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
collect2: error: ld returned 1 exit status
```
The `.travis.yml` file specifies `dist: trusty`, which suggests that the build is routinely CI tested with Ubuntu 14.04, and `g++-5`.

**Comment by giordano** [comment]
> which suggests that the build is routinely CI tested with Ubuntu 14.04, and g++-5.

CI doesn't run on Travis

**Comment by ViralBShah** [comment]
Maybe our min compiler requirements have changed and the documentation needs updating. We may want to at least update these for 1.6.
