### ISSUE TITLE
Linker errors in `build x86_64-linux-gnummtk`:  "undefined reference to `jl_gc_debug_fprint_critical_error"

### ISSUE THREAD

**Issue by fingolfin** [JuliaLang/julia#59643]
The missing function was recently introduced in PR #54835 by @topolarity .

Maybe people working on MMTK support like @d-netto or @udesou will quickly spot what the issue is?

See e.g. [this CI log](https://buildkite.com/julialang/julia-master/builds/50767/steps/canvas?sid=019976b2-df71-4956-b017-6dc8ee72c01d)

```
/usr/local/bin/../lib/gcc/x86_64-linux-gnu/9.1.0/../../../../x86_64-linux-gnu/bin/ld: ./builtins.o: in function `jl_f_intrinsic_call':
[buildroot]/src/builtins.c:2459: undefined reference to `jl_gc_debug_fprint_critical_error'
/usr/local/bin/../lib/gcc/x86_64-linux-gnu/9.1.0/../../../../x86_64-linux-gnu/bin/ld: ./signal-handling.o: in function `jl_fprint_critical_error':
[buildroot]/src/signal-handling.c:652: undefined reference to `jl_gc_debug_fprint_status'
/usr/local/bin/../lib/gcc/x86_64-linux-gnu/9.1.0/../../../../x86_64-linux-gnu/bin/ld: [buildroot]/src/signal-handling.c:653: undefined reference to `jl_gc_debug_fprint_critical_error'
/usr/local/bin/../lib/gcc/x86_64-linux-gnu/9.1.0/../../../../x86_64-linux-gnu/bin/ld: ./task.o: in function `jl_finish_task':
[buildroot]/src/task.c:355: undefined reference to `jl_gc_debug_fprint_critical_error'
/usr/local/bin/../lib/gcc/x86_64-linux-gnu/9.1.0/../../../../x86_64-linux-gnu/bin/ld: ./safepoint.o: in function `jl_safepoint_init':
[buildroot]/src/safepoint.c:109: undefined reference to `jl_gc_debug_fprint_critical_error'
/usr/local/bin/../lib/gcc/x86_64-linux-gnu/9.1.0/../../../../x86_64-linux-gnu/bin/ld: ./rtutils.o: in function `__stack_chk_fail':
[buildroot]/src/rtutils.c:246: undefined reference to `jl_gc_debug_fprint_critical_error'
/usr/local/bin/../lib/gcc/x86_64-linux-gnu/9.1.0/../../../../x86_64-linux-gnu/bin/ld: [buildroot]/usr/lib/libjulia-internal.so.1.13.0: hidden symbol `jl_gc_debug_fprint_status' isn't defined
/usr/local/bin/../lib/gcc/x86_64-linux-gnu/9.1.0/../../../../x86_64-linux-gnu/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:449: [buildroot]/usr/lib/libjulia-internal.so.1.13.0] Error 1
```
