### PR TITLE
Fix serialization of SSAValues

### LINKED ISSUE #37229: Strange TypeError on master
Repro:

```jl

using GeoGreensFunctions

xs = collect(-10.0: 5.0: 10.0)
ys = collect(-8.0: 5.0: 8.0)
zs = 4.0

xyz = Iterators.product(zs, ys, xs) |> collect
Y = [q[2] for q in xyz] |> vec
X = [q[3] for q in xyz] |> vec
Z = [q[1] for q in xyz] |> vec

stress_rect_fs(X, Y, Z, 3.0, 1.0, 0.0, 2.0, 1.0, 10.0, 75.0, 30.0, 20.0, 1.0, 0.15, 0.66e11, 0.33e11, Val(:pc))
```

gives 

```jl
ERROR: TypeError: in new, expected Tuple{Vector{Float64},Vector{Float64},Vector{Float64}}, got a value of type 
                                   Tuple{Vector{Float64},Vector{Float64},Vector{Float64}}
Stacktrace:
 [1] hcat
   @ ./array.jl:1668 [inlined]
 [2] strain_rect_fs(x::Vector{Float64}, y::Vector{Float64}, z::Vector{Float64}, x₀::Float64, y₀::Float64, depth::Float64, L::Float64, W::Float64, plunge::Float64, dip::Float64, strike::Float64, rake::Float64, slip::Float64, opening::Float64, λ::Float64, μ::Float64, ref::Val{:pc})
```

This seems to be some compilation error because it runs fine in the debugger.

Note that this function takes a long time to compile (order of a minute).

### PR DESCRIPTION
**Pull request by maleadt**
Fixes https://github.com/JuliaLang/julia/issues/37229. This was bisected to / introduced by https://github.com/JuliaLang/julia/pull/36053, marked NFC, but which changed:
https://github.com/JuliaLang/julia/blob/052315f3776e1daf419c473c8bbbbb5029029e69/src/dump.c#L488-L498
into:
https://github.com/JuliaLang/julia/blob/bd03e22518fce15d71254ca941612de786a74724/src/ircode.c#L308-L309

@JeffBezanson I'm not familiar with the how the serializer works, what was the reasoning behind this change? Other IR node types are missing from the new check too.

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Most IR node types are no longer listed there because they are all handled higher up in that function.

**Review by JeffBezanson — APPROVED** [review]

File: src/Makefile [hunk 1]
```diff
@@ -87,7 +87,7 @@ SRCS += $(RUNTIME_SRCS)
 
 # headers are used for dependency tracking, while public headers will be part of the dist
 UV_HEADERS :=
-HEADERS := $(BUILDDIR)/julia_version.h $(wildcard $(SRCDIR)/support/*.h) $(addprefix $(SRCDIR)/,julia.h julia_assert.h julia_threads.h tls.h locks.h atomics.h julia_internal.h options.h timing.h)
+HEADERS := $(BUILDDIR)/julia_version.h $(wildcard $(SRCDIR)/support/*.h) $(addprefix $(SRCDIR)/,julia.h julia_assert.h julia_threads.h tls.h locks.h atomics.h julia_internal.h options.h timing.h serialize.h)
```
Comment (vtjnash) [inline src/Makefile:90]: we usually list headers for only a couple files around lines 230, to minimize rebuilds

**Comment by vtjnash** [comment]
Looking higher up, it looks like `jl_slotnumber_type` is also not listed anymore (though much less critically so, since only generated functions should be creating more of those).

**Comment by JeffBezanson** [comment]
Might as well add it.
