### PR TITLE
separate codegen/LLVM from julia runtime

### PR DESCRIPTION
**Pull request by JeffBezanson**
This is a follow-up to #39129. The current state of the PR is that by default, everything works as normal, except during the build we generate both libjulia-internal (which does not link against LLVM) and libjulia-codegen (which does). The loader attempts to load libjulia-codegen after libjulia-internal. If that fails, it populates the codegen entry points with fallbacks in libjulia-internal that do nothing. That means you can simply delete libjulia-codegen, start with --compile=no, and enjoy a compiler-free julia runtime (assuming you don't actually need the compiler of course :smile: ).

This probably still needs a bunch of cleanup, and it also tends to segfault with --compile=no, which I assume can be fixed.

All in all, the loader framework we have is quite a nice way to separate the system into multiple optional components, and I foresee doing more of that. The parser and front-end would be another logical component to separate (and then ultimately replace with a new implementation written in julia and separately compiled!). It would be nice if we could streamline adding plugins a bit --- naturally, we thought the loader would only ever load one thing, so a few too many places need to be modified to add another.

### CODE REVIEW

**Comment by jpsamaroo** [comment]
Will dynamic dispatch still work when we just have the runtime available?

**Comment by JeffBezanson** [comment]
Yes, that is implemented in the runtime. The only parts of the language that actually need the compiler are ccall, cfunction and llvmcall.

**Comment by AriMKatz** [comment]
What's the size of the runtime? If Signatures are known, can those features be precompiled?

**Comment by JeffBezanson** [comment]
On my system:
```
-rwxrwxr-x 1 jeff jeff 11192464 Aug 30 17:09 libjulia-internal.so.1.8
-rwxrwxr-x 1 jeff jeff   266416 Aug 30 17:20 libjulia.so.1.8
```
but if you `strip` the files:
```
-rwxrwxr-x 1 jeff jeff  2757176 Aug 30 22:33 libjulia-internal.so.1.8
-rwxrwxr-x 1 jeff jeff   151096 Aug 30 22:34 libjulia.so.1.8
```

Yes, those features can be precompiled in a system image.

**Comment by imciner2** [comment]
> The only parts of the language that actually need the compiler are ccall, cfunction and llvmcall.

What does this mean for the functionality that will be available if someone uses the runtime-only part? Will it mean you can't use packages that wrap C libraries? Or would those libraries work if they are pre-compiled still?

**Comment by JeffBezanson** [comment]
Anything precompiled will work.

**Comment by vchuravy** [comment]
> The only parts of the language that actually need the compiler are ccall, cfunction and llvmcall.

For call and maybe cfunction [libffi](https://github.com/libffi/libffi) might provide an LLVM less solution

File: src/codegen.cpp [hunk 1]
```diff
@@ -8428,3 +8466,37 @@ extern void jl_write_bitcode_module(void *M, char *fname) {
...
+#include <dlfcn.h>
+#endif
+
+#include <llvm-c/Core.h>
+
+extern "C" JL_DLLEXPORT jl_value_t *jl_get_libllvm_impl(void) JL_NOTSAFEPOINT {
+#if defined(_OS_WINDOWS_)
+    HMODULE mod;
+    // FIXME: GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS on LLVMContextCreate,
+    //        but that just points to libjulia.dll
```
Comment (vtjnash) [inline src/codegen.cpp:8482]: So use `(LPCWSTR)&llvm::DebugFlag`?

File: src/gf.c [hunk 2]
```diff
@@ -2028,6 +2028,12 @@ JL_DLLEXPORT jl_value_t *jl_fptr_sparam(jl_value_t *f, jl_value_t **args, uint32
     }
 }
 
+JL_DLLEXPORT jl_callptr_t jl_fptr_args_addr = &jl_fptr_args;
+
+JL_DLLEXPORT jl_callptr_t jl_fptr_const_return_addr = &jl_fptr_const_return;
+
+JL_DLLEXPORT jl_callptr_t jl_fptr_sparam_addr = &jl_fptr_sparam;
```
Comment (vtjnash) [inline src/gf.c:2035]: use `jl_invoke_api` instead?

File: src/jl_exported_funcs.inc [hunk 3]
```diff
@@ -526,7 +511,42 @@
     XX(jl_vexceptionf) \
     XX(jl_vprintf) \
     XX(jl_wakeup_thread) \
-    XX(jl_yield) \
+    XX(jl_yield)
```
Comment (vtjnash) [inline src/jl_exported_funcs.inc:514]: for simplicity:
```suggestion
    XX(jl_yield) \

```

File: src/jl_exported_funcs.inc [hunk 4]
```diff
@@ -526,7 +511,42 @@
...
+    YY(jl_teardown_codegen) \
+    YY(jl_lock_profile) \
+    YY(jl_unlock_profile) \
+    YY(jl_create_native) \
+    YY(jl_dump_compiles) \
+    YY(jl_dump_fptr_asm) \
+    YY(jl_get_function_id) \
+    YY(jl_type_to_llvm) \
+    YY(jl_getUnwindInfo) \
+    YY(jl_get_libllvm)
```
Comment (vtjnash) [inline src/jl_exported_funcs.inc:552]:
```suggestion
    YY(jl_get_libllvm) \

```

File: cli/loader_lib.c [hunk 5]
```diff
@@ -157,31 +159,75 @@ __attribute__((constructor)) void jl_load_libjulia_internal(void) {
...
     char * curr_dep = &dep_libs[0];
+
+    // We keep track of "special" libraries names (ones whose name is prefixed with `@`)
+    // which are libraries that we want to load in some special, custom way, such as
+    // `libjulia-internal` or `libjulia-codegen`.
+    int special_idx = 0;
+    char * special_library_names[2] = {NULL};
     while (1) {
-        // try to find next colon character, if we can't, escape out.
+        // try to find next colon character, if we can't break out
```
Comment (vtjnash) [inline cli/loader_lib.c:169]:
```suggestion
        // try to find next colon character; if we can't, break out
```

File: cli/trampolines/trampolines_aarch64.S [hunk 6]
```diff
@@ -13,8 +13,9 @@ CNAME(name)##: SEP \
     br x16 SEP \
 .cfi_endproc SEP \
 
-JL_EXPORTED_FUNCS(XX)
+JL_RUNTIME_EXPORTED_FUNCS(XX)
 #ifdef _OS_WINDOWS_
-JL_EXPORTED_FUNCS_WIN(XX)
+JL_RUNTIME_EXPORTED_FUNCS_WIN(XX)
 #endif
+JL_CODEGEN_EXPORTED_FUNCS(XX)
```
Comment (vtjnash) [inline cli/trampolines/trampolines_aarch64.S:20]: It feels a little odd to be exporting the internal plugins from here, but otherwise, this PR seems to be mostly just renaming lots of (lots of) variables, so seems very straightforward. Not sure why it would be failing on CI. Are we accidentally linking part of libLLVM statically?

Comment (JeffBezanson) [reply cli/trampolines/trampolines_aarch64.S:20]: Yeah that's true; I only really did this to reuse the mechanism.

File: src/gf.c (hunk 2 above)
Comment (JeffBezanson) [reply src/gf.c:2035]: :+1: unfortunately there is one place in jitlayers.cpp that writes to it as well, so we would need to add a setter method.

File: src/Makefile [hunk 7]
```diff
@@ -45,45 +45,52 @@ RUNTIME_SRCS := \
 	simplevector runtime_intrinsics precompile \
 	threading partr stackwalk gc gc-debug gc-pages gc-stacks method \
 	jlapi signal-handling safepoint timing subtype \
-	crc32c APInt-C processor ircode opaque_closure
+	crc32c APInt-C processor ircode opaque_closure codegen-stubs
 SRCS := jloptions runtime_ccall rtutils
+ifeq ($(OS),WINNT)
+SRCS += win32_ucontext
+endif
```
Comment (vtjnash) [inline src/Makefile:53]: FLAGS now needs `-Wno-return-type-c-linkage` (on clang)

File: cli/list_strip_symbols.h [hunk 8]
```diff
@@ -3,8 +3,9 @@
...
 #include "trampolines/common.h"
 #define XX(x) --strip-symbol=CNAME(x)
-JL_EXPORTED_FUNCS(XX)
+JL_RUNTIME_EXPORTED_FUNCS(XX)
 #ifdef _OS_WINDOWS_
-JL_EXPORTED_FUNCS_WIN(XX)
+JL_RUNTIME_EXPORTED_FUNCS_WIN(XX)
 #endif
+JL_CODEGEN_EXPORTED_FUNCS(XX)
 #undef XX
```
Comment (vtjnash) [inline cli/list_strip_symbols.h:11]: I forget we did this. I think we can delete this now?

Comment (vtjnash) [reply cli/list_strip_symbols.h:11]: @staticfloat

Comment (staticfloat) [reply cli/list_strip_symbols.h:11]: Mmmm, yeah, we probably won't run into the same symbol conflicts anymore.  Let's try it!

**Comment by JeffBezanson** [comment]
Looks ready to go!! :tada: :partying_face:

**Comment by timholy** [comment]
> Anything precompiled will work.

Might be worth clarifying (to avoid misunderstanding): presumably this means "precompiled to native code." I.e., not (currently) useful in conjunction with ordinary package precompilation, but quite useful for a sysimage.

**Comment by VarLad** [comment]
Will this be a part of 1.8 release?

**Comment by oscardssmith** [comment]
If it gets done in time.

**Comment by DilumAluthge** [comment]
I'm seeing the following `asan` failure on master, starting with this PR:

```
LINK tmp/test-asan/asan/usr/lib/libjulia-codegen-debug.so.1
LINK tmp/test-asan/asan/usr/lib/libjulia-codegen-debug.so
make[1]: Leaving directory '/cache/build/amdci5-3/julialang/julia-master/tmp/test-asan/asan/src'
make[1]: Entering directory '/cache/build/amdci5-3/julialang/julia-master/tmp/test-asan/asan'
JULIA tmp/test-asan/asan/usr/lib/julia/corecompiler.ji
: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
Aborted
make[1]: *** [/cache/build/amdci5-3/julialang/julia-master/sysimage.mk:61: /cache/build/amdci5-3/julialang/julia-master/tmp/test-asan/asan/usr/lib/julia/corecompiler.ji] Error 134
make[1]: Leaving directory '/cache/build/amdci5-3/julialang/julia-master/tmp/test-asan/asan'
make: *** [/cache/build/amdci5-3/julialang/julia-master/Makefile:82: julia-sysimg-ji] Error 2
make: Leaving directory '/cache/build/amdci5-3/julialang/julia-master/tmp/test-asan/asan'
🚨 Error: The command exited with status 2
```

Example logs:
1. https://buildkite.com/julialang/julia-master/builds/4382#b5852d7b-8250-48b9-a8e1-effe2e848e24
2. https://buildkite.com/julialang/julia-master/builds/4382#3dc2e675-9fe1-46ef-b9b6-12108234ff9f

Is this failure related to this PR?

cc: @tkf @JeffBezanson

**Comment by DilumAluthge** [comment]
Also cc: @vchuravy

**Comment by JeffBezanson** [comment]
Ok I'm guessing this is due to linking two copies of a small subset of LLVM libraries, since libjulia-internal statically links `-lLLVMSupport -lLLVMDemangle`, and libjulia-codegen dynamically links all of LLVM. Not yet sure what to do about it.

**Comment by DilumAluthge** [comment]
@tkf Is there a way that we can tell ASAN to "skip" this particular check (the check that's detecting the duplicate command line options)? And then we can re-enable this check once we figure out how to fix the issue.

**Comment by JeffBezanson** [comment]
We are; I guess command line options are handled in libLLVMSupport?

**Comment by vtjnash** [comment]
CI is also now failing on macOS due to a conflict between this PR and the update to LLVM: https://build.julialang.org/#/builders/63/builds/4301

**Comment by vtjnash** [comment]
one possible solution is to detect if it is loaded twice:
```diff
diff --git a/cli/loader_lib.c b/cli/loader_lib.c
index abc144c41c..81bb25062d 100644
--- a/cli/loader_lib.c
+++ b/cli/loader_lib.c
@@ -197,6 +197,11 @@ __attribute__((constructor)) void jl_load_libjulia_internal(void) {
 
     // Unpack our special library names.  This is why ordering of library names matters.
     libjulia_internal = load_library(special_library_names[0], lib_dir, 1);
+
+    void (*pZN4llvm2cl22ResetCommandLineParserEv)(void) = (void (*)(void))lookup_symbol(libjulia_internal, "_ZN4llvm2cl22ResetCommandLineParserEv");
+    if (pZN4llvm2cl22ResetCommandLineParserEv)
+       pZN4llvm2cl22ResetCommandLineParserEv();
+
     void *libjulia_codegen = load_library(special_library_names[1], lib_dir, 0);
     const char * const * codegen_func_names;
     if (libjulia_codegen == NULL) {
@@ -219,7 +224,7 @@ __attribute__((constructor)) void jl_load_libjulia_internal(void) {
     }
     // jl_options must be initialized very early, in case an embedder sets some
     // values there before calling jl_init
-    ((void (*)())jl_init_options_addr)();
+    ((void (*)(void))jl_init_options_addr)();
 
     for (unsigned int symbol_idx=0; codegen_func_names[symbol_idx] != NULL; ++symbol_idx) {
         void *addr = lookup_symbol(libjulia_codegen, codegen_func_names[symbol_idx]);
```

**Comment by chriselrod** [comment]
Git bisect blames this commit:
```
git bisect bad                                                                                 (base)
628209c1f2f746e3fc21ccd7cb34e67289403d44 is the first bad commit
commit 628209c1f2f746e3fc21ccd7cb34e67289403d44
Author: Jeff Bezanson <jeff.bezanson@gmail.com>
Date:   Tue Oct 5 16:14:00 2021 -0400

    separate codegen/LLVM from julia runtime (#41936)

    separate libjulia-internal and libjulia-codegen

    makes codegen optional via a plugin interface

    Add special `@` character to `LOADER_BUILD_DEP_LIBS` and friends

    This allows us to mark a library as `"special"` so that the loader
    doesn't attempt to open it blindly, but rather interprets it as a list
    of positional arguments, that it knows how to interpret.  We strictly
    require exactly the number of special libraries, to help avoid errors in
    the future as we add to this list.

    Strip windows runtime symbols from the windows import library

    Without stripping these symbols out of the import library, we end up with duplicate symbol definition errors.

    Co-authored-by: Julian Samaroo <jpsamaroo@jpsamaroo.me>

    Co-authored-by: Elliot Saba <staticfloat@gmail.com>
```
for this ICE while building `src/runtime_intrinsics.so`:
```
> make                                                                                               (base)
removed './bin/7z'
    CC src/runtime_intrinsics.o
during RTL pass: expand
/home/chriselrod/Documents/languages/julia/src/runtime_intrinsics.c: In function 'jl_copysign_float':
/home/chriselrod/Documents/languages/julia/src/runtime_intrinsics.c:1065:1: internal compiler error: Segmentation fault
 1065 | }
      | ^
/home/chriselrod/Documents/languages/julia/src/runtime_intrinsics.c:1322:1: note: in expansion of macro 'bi_fintrinsic'
 1322 | bi_fintrinsic(copysign_float,copysign_float)
      | ^~~~~~~~~~~~~
0x8d91c9 crash_signal
        ../../gcc-11.2.0/gcc/toplev.c:327
0x7f14b05c5e4f ???
        ../sysdeps/unix/sysv/linux/libc_sigaction.c:10
0x1170fda mark_jump_label_1
        ../../gcc-11.2.0/gcc/jump.c:1097
0x117104f mark_jump_label_1
        ../../gcc-11.2.0/gcc/jump.c:1221
0x117104f mark_jump_label_1
        ../../gcc-11.2.0/gcc/jump.c:1221
0x1170cb3 mark_jump_label(rtx_def*, rtx_insn*, int)
        ../../gcc-11.2.0/gcc/jump.c:1084
0x1170cb3 mark_all_labels
        ../../gcc-11.2.0/gcc/jump.c:332
0x1170cb3 rebuild_jump_labels_1
        ../../gcc-11.2.0/gcc/jump.c:74
0x1087d5f execute
        ../../gcc-11.2.0/gcc/cfgexpand.c:6811
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
make[1]: *** [Makefile:215: runtime_intrinsics.o] Error 1
make: *** [Makefile:76: julia-src-release] Error 2
```

**Comment by DilumAluthge** [comment]
@chriselrod Can you open a new issue?

**Comment by chriselrod** [comment]
> @chriselrod Can you open a new issue?

Done: #42588.

**Comment by pemryan** [comment]
> 
re-implement _ccall_ via _libffi_ maybe a nice move.

I tried Julia 1.8.0 (2021-12-06)  Commit 30fe8cc2c1*, and found there exists such a dependency chain:

LinearAlgebra --> Linearlibblastrampoline_jll --> OpenBLAS_jll -->  ccall --> compiler

 which makes LLVM a must-have library at runtime.
