### PR TITLE
[release-0.5] backports for 0.5.0-rc3

### PR DESCRIPTION
**Pull request by tkelman**
@nanosoldier `runbenchmarks(ALL, vs = "@0350e5769b43f56c4c570741b0f5b2edf9399dc7")` (vs rc2 tag)

will be running pkgeval here to check for any regressions

### CODE REVIEW

**Comment by tkelman** [comment]
only added a few commits since the previous trigger, but will be a good sanity check for what's noise:
@nanosoldier `runbenchmarks(ALL, vs = "@0350e5769b43f56c4c570741b0f5b2edf9399dc7")` (vs rc2 tag)

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/18156) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/9c6c4ef1fc0050ab30cf141ab5ce280e6675cb2c/6a2f655_vs_0350e57/report.md). cc @jrevels

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/18156#issuecomment-241189452) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/33c12deffc8345c4cc584f6eac6ae8fe6ab5a64e/8d99c3a_vs_0350e57/report.md). cc @jrevels

**Comment by maleadt** [comment]
I've put the ASAN-related changes (#18067, #18143, #18054, and part of #17727) in [a branch of mine](https://github.com/JuliaLang/julia/commits/tb/backport_asan), currently testing on my ASAN buildbot and awaiting a LGTM from @yuyichao on the #17727 part.

**Comment by tkelman** [comment]
See the cherry picking procedure in https://github.com/JuliaLang/julia/issues/17418 to make sure the cross references are all recorded

**Comment by tkelman** [comment]
@jrevels did I break nanosoldier somehow? would be very good to get it back since there are regressions here I haven't tracked down yet.

**Comment by jrevels** [comment]
The server fell over for some weird libuv-related reason. I've restarted it, try again?

**Comment by ViralBShah** [comment]
The parallel make doesn't seem to be working correctly between curl and libssh2.

**Comment by JeffBezanson** [comment]
This probably needs #18126

**Comment by tkelman** [comment]
@nanosoldier `runbenchmarks(ALL, vs = "@0350e5769b43f56c4c570741b0f5b2edf9399dc7")` (merge commit at 69a605bad0d0e0be00eb545a14e1385a732533e4 vs rc2 tag)

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/18156#issuecomment-241286883) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/35149fa7e388382bdada05782ba212849ba7d098/510feea_vs_0350e57/report.md). cc @jrevels

**Comment by tkelman** [comment]
Nice. I think we can ship that. My PkgEval run last night got stuck (termination with `timeout` still isn't working properly), so will wait to see what a re-run I started a few hours ago says.

**Comment by tkelman** [comment]
because I'm curious - @nanosoldier `runbenchmarks(ALL, vs = "@0030eec2f332f353e6890ca289ac2aca55532dde")` (merge commit at fafdc7b8a3d365f03325f8fbb145e4ccf883c85e vs rc0 tag)

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/18156#issuecomment-241304411) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/c752e57e90fef83e53a483e3915022f4a02ceb95/dde805c_vs_0030eec/report.md). cc @jrevels

**Comment by tkelman** [comment]
A few failures (and 5 improvements, apparently): https://gist.github.com/d048e155d5e7a33b00e5f8220b43ea27

- BandedMatrices has one of its tests that is sensitive to what type of exception is getting thrown in a promotion
- BaseTestDeprecated has a `UndefVarError: successflag not defined` - possibly related to @yuyichao's testset changes?
- CustomUnitRanges got a `MethodError` when it expected a `BoundsError`, cc @timholy
- DSP.jl was broken by @timholy's FFT changes: `type Complex{Float64} not supported\n in _fftwfloat(::Type{Complex{Float64}}) at ./dft.jl:27\n in fft(::Array{Complex{Int64},1}) at ./dft.jl:205\n in #periodogram#1(::Bool, ::Int64, ::Int64, ::Void, ::Function, ::Array{Complex{Int64},1}) at /home/vagrant/.julia/v0.5/DSP/src/periodograms.jl:224\n in (::DSP.Periodograms.#kw##periodogram)(::Array{Any,1}, ::DSP.Periodograms.#periodogram, ::Array{Complex{Int64},1}) at ./<missing>:0\n in include_from_node1(::String) at ./loading.jl:426 (repeats 2 times)\n in process_options(::Base.JLOptions) at ./client.jl:262\n in _start() at ./client.jl:318\nwhile loading /home/vagrant/.julia/v0.5/DSP/test/periodograms.jl, in expression starting on line 44`
- ImageProjectiveGeometry got stuck with a `LOCKERROR: It looks like conda is already doing something.` from Conda.jl - looking at the logs, I think the lock problem began when the same VM was adding IJulia - @Luthaf @stevengj have you ever seen this?
- KrylovMethods had a tolerance problem `Test Failed\n  Expression: norm(conA - (x1[3])[end,end]) / conA < 1.0e-12\n   Evaluated: 0.41156489116875644 < 1.0e-12` but that's a big enough difference that it's worth looking into seeing whether it's repeatable. This package is generally flaky (http://pkg.julialang.org/detail/KrylovMethods.html, cc @lruthotto) but usually the differences are smaller
- Lora hit https://github.com/JuliaLang/julia/issues/17932
- NetCDF was tripped up by the same conda lock problem as ImageProjectiveGeometry (it ran in the same worker)
- ValueHistories also hit #17932

**Comment by tkelman** [comment]
Sorry @yuyichao, the BaseTestDeprecated UndefVarError was caused by https://github.com/JuliaLang/julia/pull/18130 - that's getting reverted for now.

**Comment by yuyichao** [comment]
> Sorry @yuyichao, the BaseTestDeprecated UndefVarError was caused by #18130 - that's getting reverted for now.

Cool. I've also just verified that a commit after the test change is not affected and have just started bisecting.... FWIW, I don't think the package is related to the Base.Test in 0.5+ at all.

**Comment by yuyichao** [comment]
Also, it seems that the test at https://github.com/JuliaCI/BaseTestDeprecated.jl/blob/master/test/runtests.jl#L38 is potentially not testing what it wants to test. The `successflag` and `failureflag` before the first assignment and the `failureflag` before the second assignment are all undefined reference to local variables. @IainNZ

**Comment by tkelman** [comment]
pretty obvious, but #17980 is what caused the ambiguity failure in CustomUnitRanges

#17953 triggered the inference error in Lora and ValueHistories, so I'm tempted to revert that too - though it may also require reverting some of the followups to avoid conflicts.

**Comment by tkelman** [comment]
@nanosoldier `runbenchmarks(ALL, vs = "@0350e5769b43f56c4c570741b0f5b2edf9399dc7")` (merge commit at fd14be9 vs rc2 tag)

**Comment by timholy** [comment]
Instead of reverting the DFT change, can you cherry pick #18178?

**Comment by tkelman** [comment]
@nanosoldier `runbenchmarks(ALL, vs = "@0350e5769b43f56c4c570741b0f5b2edf9399dc7")` (merge commit at 2406ed9 vs rc2 tag)

**Comment by tkelman** [comment]
I'm running PkgEval again at https://github.com/JuliaLang/julia/commit/2406ed91a2f0ab9e81b21f30eba769816b7d4553, with only #18130 reverted and fixes cherry-picked from #18046 and #18178.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/18156#issuecomment-241392099) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/d74f965aaa30a3bd2102d8b572ffce0d603f6231/8ae2344_vs_0350e57/report.md). cc @jrevels

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/18156#issuecomment-241404159) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/5e2c33d74c28976a14549946cccc4ad9fb33fe1f/cc9396a_vs_0350e57/report.md). cc @jrevels

**Comment by lruthotto** [comment]
As for KrylovMethods: I could not reproduce the issue on my machine and I've changed the test. Previously the direction was chosen randomly (which caused the test to fail sometimes). Now, it is fixed and should always work.

**Comment by tkelman** [comment]
@nanosoldier `runbenchmarks(ALL, vs = "@0350e5769b43f56c4c570741b0f5b2edf9399dc7")` (merge commit at e5b8332 vs rc2 tag)

@JeffBezanson are you going to merge https://github.com/JuliaLang/julia/pull/18046 ?

**Comment by JeffBezanson** [comment]
Merged.

**Comment by tkelman** [comment]
At 2406ed9 we only had the known exception type change with BandedMatrices, and a tolerances-too-tight random failure in PolynomialRoots: https://gist.github.com/08599e229e722ec059f90a17ea5259fc

I'm hoping that https://github.com/JuliaLang/julia/pull/18183 won't have any unintended consequences.

**Comment by nanosoldier** [comment]
[Your benchmark job](https://github.com/JuliaLang/julia/pull/18156#issuecomment-241539747) has completed - possible performance regressions were detected. A full report can be found [here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/b84ec0d0b95d5dcde5ee9b1f56f9686ce8d25b6e/b3b8ce2_vs_0350e57/report.md). cc @jrevels

**Comment by ufechner7** [comment]
Is there an explanation for the performance degration in the BitArray tests?

**Comment by KristofferC** [comment]
Probably #18046?

**Comment by tlnagy** [comment]
@tkelman What about https://github.com/JuliaLang/julia/pull/18122? It's causing Gadfly's doctests to fail on RC3 still. I would appreciate if it was backported.

**Comment by tkelman** [comment]
https://github.com/JuliaLang/julia/commit/ca5c823bb34fd4dbd511aa8b022f5b52d177fe06 it's in there

**Comment by tlnagy** [comment]
Seems like it didn't completely fix the problem (using Gadfly master) because:

```
julia> using RDatasets

julia> using Gadfly

julia> plot(dataset("ggplot2", "diamonds"), x="Price", color="Cut",
            Geom.histogram(bincount=30, density=true))
Error showing value of type Gadfly.Plot:
ERROR: InexactError()
 in copy!(::Base.LinearFast, ::Array{Int64,1}, ::Base.LinearFast, ::Array{Float64,1}) at ./abstractarray.jl:559
 in broadcast!(::Base.#identity, ::Array{Int64,1}, ::Array{Float64,1}) at ./broadcast.jl:24
 in apply_statistic(::Gadfly.Stat.HistogramStatistic, ::Dict{Symbol,Gadfly.ScaleElement}, ::Gadfly.Coord.Cartesian, ::Gadfly.Aesthetics) at /Users/tamasnagy/.julia/v0.5/Gadfly/src/statistics.jl:330
 in apply_statistics(::Array{Gadfly.StatisticElement,1}, ::Dict{Symbol,Gadfly.ScaleElement}, ::Gadfly.Coord.Cartesian, ::Gadfly.Aesthetics) at /Users/tamasnagy/.julia/v0.5/Gadfly/src/statistics.jl:38
 in render_prepare(::Gadfly.Plot) at /Users/tamasnagy/.julia/v0.5/Gadfly/src/Gadfly.jl:740
 in render(::Gadfly.Plot) at /Users/tamasnagy/.julia/v0.5/Gadfly/src/Gadfly.jl:799
 in display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::MIME{Symbol("text/html")}, ::Gadfly.Plot) at /Users/tamasnagy/.julia/v0.5/Gadfly/src/Gadfly.jl:1062
 in macro expansion at ./multimedia.jl:143 [inlined]
 in display(::Gadfly.Plot) at /Users/tamasnagy/.julia/v0.5/Gadfly/src/Gadfly.jl:1014
 in print_response(::Base.Terminals.TTYTerminal, ::Any, ::Void, ::Bool, ::Bool, ::Void) at ./REPL.jl:154
 in print_response(::Base.REPL.LineEditREPL, ::Any, ::Void, ::Bool, ::Bool) at ./REPL.jl:139
 in (::Base.REPL.##22#23{Bool,Base.REPL.##33#42{Base.REPL.LineEditREPL,Base.REPL.REPLHistoryProvider},Base.REPL.LineEditREPL,Base.LineEdit.Prompt})(::Base.LineEdit.MIState, ::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Bool) at ./REPL.jl:652
 in run_interface(::Base.Terminals.TTYTerminal, ::Base.LineEdit.ModalInterface) at ./LineEdit.jl:1579
 in run_interface(::Base.Terminals.TTYTerminal, ::Base.LineEdit.ModalInterface) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in run_frontend(::Base.REPL.LineEditREPL, ::Base.REPL.REPLBackendRef) at ./REPL.jl:903
 in run_repl(::Base.REPL.LineEditREPL, ::Base.##930#931) at ./REPL.jl:188
 in _start() at ./client.jl:360
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?

julia> versioninfo()
Julia Version 0.5.0-rc3+0
Commit e6f843b (2016-08-22 23:43 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by tkelman** [comment]
How's master? Worth a new issue probably?

**Comment by tlnagy** [comment]
Testing right now. New issue here: https://github.com/dcjones/Gadfly.jl/issues/880. I'll open one against Base once we figure out what's wrong.
