### ISSUE TITLE
constant redefinition after workspace() fails on master under some circumstances

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#22434]
Consider:

```julia
const X = 1
workspace()
const X = []
```

On master, putting this in a file and running it results in an error (`ERROR: LoadError: invalid redefinition of constant X`), although pasting it into the REPL works. It works in both cases on 0.6.

This functionality was useful for package tests, but the docs do say that "This function should only be used interactively." However, I can also make it fail at the REPL if that is desired:

```julia
julia> const X = 1; workspace(); const X = []
ERROR: invalid redefinition of constant X
```

**Comment by simonster** [comment]
Labeling this as "doc" since @vtjnash says it is working as intended.

**Comment by vtjnash** [comment]
What else do you want it to document? As you noted, they already say it will only work interactively.

**Comment by simonster** [comment]
I feel like any change that breaks actual existing code deserves a note in NEWS, if for no other reason that you can point people who realize that their code is broken to that note. In this case, I was using `workspace()` in some test code, and it would have been useful to know that the breakage was intended and can be worked around using `@eval Core.Main ...` after `workspace()`.

**Comment by simonster** [comment]
Also worth noting that, on master but not 0.6, constant redefinition after `workspace()` appears to be totally broken in IJulia:

<img width="700" alt="screen shot 2017-06-21 at 1 53 56 pm" src="https://user-images.githubusercontent.com/470884/27406369-7701d17e-5689-11e7-8be9-dfd2c5cee32b.png">
